"""Enumerate every command/acquisition/delegation rule; emit reviewable Markdown.

This is an inventory and permission guard check, not an engine safety proof.
Controller-level causality/compatibility is maintained in TASK-OWNERSHIP.md.
No source is changed. --patch emits apply_patch input for the inventory only.
"""
from collections import Counter
import difflib
import hashlib
from pathlib import Path
import re
import sys
from validate_naval_doctrine import rule_blocks

ROOT = Path(__file__).resolve().parents[1]
OPS = re.compile(r'\((up-(?:retreat-now|reset-attack-now|reset-unit|target-objects|target-point|'
                 r'create-group|modify-group-flag|reset-group|find-local|find-remote|set-group|'
                 r'add-object-by-id|assign-builders|build|build-line|request-hunters|retask-gatherers)'
                 r'|attack-now|build|build-forward|build-wall|build-gate|fe-exclude-from-attack-group)\b([^()]*)\)')
NATIVE = re.compile(r'\((?:set-strategic-number|up-modify-sn) (sn-[\w-]*(?:explor|attack|defend|'
                    r'gatherer|builder|repair|task-ungrouped)[\w-]*)\b([^()]*)\)')
DIRECT = re.compile(r'\(up-target-(?:point|objects)\b')


def inventory():
    rows, failures = [], []
    for path in sorted(ROOT.glob('*.per')):
        text = path.read_text(encoding='utf-8-sig')
        for a, b, body, facts, actions in rule_blocks(text):
            code = '\n'.join(line.split(';')[0] for line in actions.splitlines())
            operations = [m[0] for m in OPS.finditer(code)]
            native = [m[0] for m in NATIVE.finditer(code)]
            if not operations and not native:
                continue
            line = text.count('\n', 0, a) + 1
            for command in DIRECT.finditer(code):
                prefix = code[:command.start()]
                if 'object-data-player != my-player-number' not in prefix or 'object-data-group-flag' not in prefix:
                    failures.append(f'{path.name}:{line}: direct writer lacks self/ownership permission check')
            if re.search(r'\(up-(retreat-now|reset-attack-now|reset-unit)\b', code):
                failures.append(f'{path.name}:{line}: global task destruction remains')
            states = re.findall(r'\(goal ([^()]*)\)', facts)
            if not states:
                states = [' '.join(facts.split())[:190]]
            selectors = [s for s in operations if re.match(r'\(up-(find-local|find-remote|set-group|add-object-by-id)', s)]
            writers = [s for s in operations if s not in selectors] + native
            filters = re.findall(r'\(up-remove-objects search-local object-data-(?:group-flag|player|idling|id) [^()]+\)', code)
            metadata = [s for s in writers if re.match(r'\(up-(create-group|modify-group-flag|reset-group)', s)]
            delegated = bool(native or any(re.match(r'\((?:build|up-build|up-assign-builders|up-request-hunters|up-retask-gatherers|attack-now)\b', s) for s in writers))
            verdict = 'C / bounded native admission; engine acceptance pending' if delegated else 'D / cooperative permission path'
            if not writers:
                verdict = 'D / search or census; no order or ownership mutation here'
            rows.append(dict(file=path.name, line=line, states=states, selectors=selectors,
                             writers=writers, filters=list(dict.fromkeys(filters)), metadata=metadata,
                             verdict=verdict, hold='(goal gl-owner-worker-hold NO)' in facts))
    return rows, failures


def cell(values):
    return '<br>'.join('`' + v.replace('|', '\\|') + '`' for v in values) or '-'


def render():
    rows, failures = inventory()
    digest = hashlib.sha256()
    for path in sorted(ROOT.glob('*.per')):
        digest.update(path.name.encode())
        digest.update(path.read_text(encoding='utf-8-sig').replace('\r\n', '\n').encode())
    out = ['# Ownership source inventory - T11', '',
           'Generated by `tools/audit_ownership_source.py --patch`; reviewed with the owner/fault/compatibility matrix in [TASK-OWNERSHIP.md](TASK-OWNERSHIP.md).', '',
           f'Logical PER source SHA-256: `{digest.hexdigest()}`. **{len(rows)} relevant rule sites**. This inventory counts actual rules, not the old approximate audit totals.', '',
           'Each row contains its acquisition/affected unit types, command or native delegation, and the concrete permission filters. Release and legitimate preemption are owner-wide contracts in the matrix; metadata operations below identify every rule which can acquire/release a reservation. Search-only rows are not silently treated as commands. D means source-level cooperative ownership safety, NOT pathfinding/targeting/engine validation. C names a native boundary; the matrix specifies the suppression applied and the one controlled acceptance experiment.', '',
           'Direct commands are rechecked immediately at issuance. Delayed hull/passenger consumers use persistent IDs/groups; same-pass selection/consumer chains retain their filtered lists. Pass-start group hygiene removes converted/other-owner references before legacy release operations. FREE means negative group flag, self-owned, with role/task exclusions shown below; military idle eligibility is an additional acquisition requirement, not a claim that villagers support the same idle predicate.', '',
           '| File | Relevant rules |', '|---|---:|']
    out += [f'| {name} | {count} |' for name, count in sorted(Counter(r['file'] for r in rows).items())]
    out += ['', '## Complete rule-site matrix', '',
            '| File / rule line | Owner state / eligibility | Acquisition / units | Commands, delegation, reservation / release | Concrete ownership revalidation | Classification / correction |',
            '|---|---|---|---|---|---|']
    for r in rows:
        guards = cell(r['filters'])
        if r['hold']:
            guards += '<br>`gl-owner-worker-hold NO` admission gate'
        out.append(f'| [{r["file"]}:{r["line"]}]({r["file"]}#L{r["line"]}) | {cell(r["states"])} | {cell(r["selectors"])} | {cell(r["writers"])} | {guards} | {r["verdict"]} |')
    out += ['', '## Guard audit', '', 'PASS: no unguarded direct writer or global reset/retreat remains.' if not failures else '\n'.join(failures), '']
    return '\n'.join(out)


if __name__ == '__main__':
    rows, failures = inventory()
    if '--patch' not in sys.argv:
        print(f'{len(rows)} relevant sites; {len(failures)} direct permission failures')
        print('\n'.join(failures))
        raise SystemExit(bool(failures))
    path = ROOT / 'OWNERSHIP-SOURCE-INVENTORY.md'
    new = render()
    print('*** Begin Patch')
    if path.exists():
        old = path.read_text(encoding='utf-8')
        print('*** Update File: ' + path.as_posix())
        for line in list(difflib.unified_diff(old.splitlines(), new.splitlines(), n=3))[2:]:
            print('@@' if line.startswith('@@') else line)
    else:
        print('*** Add File: ' + path.as_posix())
        print('\n'.join('+' + line for line in new.splitlines()))
    print('*** End Patch')
