"""Observed enemy class census for bounded reactive Skirmisher production."""
from pathlib import Path
import argparse
from generate_assault_missions import rule
ROOT = Path(__file__).resolve().parents[1]

def generate():
    fields = ('threat', 'clock', 'next', 'scan', 'focus', 'local', 'local-last', 'remote', 'remote-last')
    out = [';Generated by tools/generate_ranged_threat.py. No orders or ownership changes.',
           ';AIRef: players-unit-type-count cannot count enemy classes.',
           ';Search only recently sighted enemies; no omniscient cc fact. Five-second refresh.']
    out += [f'(defconst gl-reactive-ranged-{name} {15860+i})' for i,name in enumerate(fields)]
    def add(f,a): out.append(rule(f,a))
    add(['(true)'], ['(set-goal gl-reactive-ranged-next 0)', '(set-goal gl-reactive-ranged-threat NO)', '(disable-self)'])
    add(['(true)'], ['(up-get-fact game-time 0 gl-reactive-ranged-clock)', '(set-goal gl-reactive-ranged-scan NO)'])
    add(['(up-compare-goal gl-reactive-ranged-clock g:>= gl-reactive-ranged-next)'], [
        '(set-goal gl-reactive-ranged-scan YES)', '(set-goal gl-reactive-ranged-threat NO)',
        '(up-modify-goal gl-reactive-ranged-focus s:= sn-focus-player-number)',
        '(up-modify-goal gl-reactive-ranged-next g:= gl-reactive-ranged-clock)',
        '(up-modify-goal gl-reactive-ranged-next c:+ 5)'])
    for p in range(1,9):
        for kind in ('archery-class', 'cavalry-archer-class'):
            f=['(goal gl-reactive-ranged-scan YES)', '(goal gl-reactive-ranged-threat NO)', f'(player-in-game {p})', f'(stance-toward {p} enemy)']
            add(f,[f'(set-strategic-number sn-focus-player-number {p})', '(up-full-reset-search)',
                f'(up-find-remote c: {kind} c: 3)', '(up-get-search-state gl-reactive-ranged-local)'])
            add([*f,'(up-compare-goal gl-reactive-ranged-remote c:>= 3)'],['(set-goal gl-reactive-ranged-threat YES)'])
    add(['(goal gl-reactive-ranged-scan YES)'],['(up-full-reset-search)', '(up-modify-sn sn-focus-player-number g:= gl-reactive-ranged-focus)'])
    return '\n\n'.join(out)+'\n'

if __name__ == '__main__':
    p=argparse.ArgumentParser(); p.add_argument('--write',action='store_true'); a=p.parse_args()
    path=ROOT/'rawai-reactive-ranged-threat.per'; expected=generate()
    if a.write: path.write_bytes(expected.replace('\n','\r\n').encode())
    else:
        assert path.read_text()==expected, 'reactive ranged census drift'
        print('reactive ranged census synchronized')
