"""Local right-of-way: observe a real moving hull twice before yielding ONE cog.

No DUC group is acquired, no priority hull is ordered, no global economy SN is
changed. Three temporary merchant records, four hull cooldowns; never evict a
live cooldown to make room. The actual emitted rules are exercised by fixtures.
"""
from pathlib import Path
import argparse
from generate_assault_missions import rule

ROOT=Path(__file__).resolve().parents[1]
FIELDS=('clock','next','stage','hull','cursor','stalls','tries','active','kind','zone',
        'distance','moved','turned','merchant','record','side','focus','safe','found',
        'x','y','last-x','last-y','dest-x','dest-y','old-dest-x','old-dest-y',
        'hold-x','hold-y','bounded-x','bounded-y','merchant-x','merchant-y','count','until','issued')
RECORD=('id','until','hold-until','next','renewals','target','x','y','zone')


def definitions():
    names=list(FIELDS)+[f'm{i}-{k}' for i in range(3) for k in RECORD]+[f'ban{i}-{k}' for i in range(4) for k in ('id','until')]
    return ';Generated naval right-of-way storage; no DUC group/timer aliases.\n'+'\n'.join(
        f'(defconst gl-row-{name} {15700+i})' for i,name in enumerate(names))+'\n'


def generate():
    out=[';Generated by tools/generate_naval_right_of_way.py. Diagnostic IDs:',
         ';420 yielded merchant, 421 stalled priority hull; bounded to 3 per hull cooldown.',
         ';A hold lasts at most 32s (three renewals); merchant eligibility cooldown 120s.',
         ';Only live movement/transport/unload intent is assisted; waiting/firing is not a stall.']
    def add(f,a): out.append(rule(f,a))
    def st(n): return [f'(goal gl-row-stage {n})']
    def owner(): return ['(up-remove-objects search-local object-data-player != my-player-number)',
                        '(up-remove-objects search-local object-data-group-flag >= 0)']
    def select(name): return ['(up-full-reset-search)',f'(up-add-object-by-id search-local g: {name})']
    def end(): return ['(up-modify-goal gl-row-cursor g:= gl-row-hull)', '(set-goal gl-row-hull -1)',
                      '(set-goal gl-row-active 0)', '(set-goal gl-row-stage 0)']
    transport_intent='(or (up-object-data object-data-action == actionid-move)\n\t(or (up-object-data object-data-action == actionid-transport) (up-object-data object-data-action == actionid-unload)))'
    init=['(set-goal gl-row-next 0)', '(set-goal gl-row-stage 0)', '(set-goal gl-row-hull -1)',
          '(set-goal gl-row-cursor -1)', '(set-goal gl-row-active 0)']
    for i in range(3): init += [f'(set-goal gl-row-m{i}-id -1)',f'(set-goal gl-row-m{i}-until 0)']
    for i in range(4): init += [f'(set-goal gl-row-ban{i}-id -1)',f'(set-goal gl-row-ban{i}-until 0)']
    add(['(true)'],[*init,'(disable-self)'])
    add(['(true)'],['(up-get-fact game-time 0 gl-row-clock)', '(set-goal gl-row-issued 0)'])
    for i in range(4):
        add([f'(up-compare-goal gl-row-clock g:>= gl-row-ban{i}-until)'],[f'(set-goal gl-row-ban{i}-id -1)'])
    # Expired hold/cooldown records remain identified until a new lease can
    # safely replace them; release below runs before a new record is allocated.
    hold_start=len(out)
    for i in range(3):
        m=f'gl-row-m{i}'
        live=[f'(up-compare-goal {m}-id c:>= 0)', f'(up-compare-goal gl-row-clock g:>= {m}-next)']
        add(live,[*select(m+'-id'),*owner(), '(up-remove-objects search-local object-data-class != trade-cog-class)',
            '(up-remove-objects search-local object-data-under-attack > 0)',
            f'(up-remove-objects search-local object-data-map-zone-id g:!= {m}-zone)',
            f'(up-set-target-point {m}-x)', '(set-goal gl-row-found 0)', '(set-goal gl-row-safe 0)'])
        add([*live,'(up-set-target-object search-local c: 0)'],['(set-goal gl-row-found 1)'])
        add([*live,'(goal gl-row-found 0)'],[f'(set-goal {m}-hold-until 0)'])
        holding=[*live,'(goal gl-row-found 1)', '(goal gl-row-active 1)',
                 f'(up-compare-goal gl-row-clock g:< {m}-hold-until)', f'(up-compare-goal {m}-renewals c:< 3)']
        # Do not accept action-move by itself as proof that the yield survived.
        # Native trade may replace our single-hull order with a fleet MOVE in the
        # same second. Renew only when that MOVE no longer targets this record's
        # holding point, or when native trade/idle reacquisition is visible.
        add([*holding,'(goal gl-row-issued 0)', '(up-set-target-object search-local c: 0)',
             f'(or (up-object-data object-data-action == actionid-trade)\n\t(or (and (up-object-data object-data-idling == 1) (up-object-data object-data-distance > 3))\n\t(and (up-object-data object-data-action == actionid-move)\n\t\t(or (up-object-data object-data-move-x g:!= {m}-x) (up-object-data object-data-move-y g:!= {m}-y)))))',
             f'(up-path-distance {m}-x 1 != 65535)'], [*owner(),
            f'(up-target-point {m}-x action-move -1 stance-no-attack)', f'(up-modify-goal {m}-renewals c:+ 1)', '(set-goal gl-row-issued 1)'])
        release=[*live, '(or (goal gl-row-active 0) '+f'(up-compare-goal gl-row-clock g:>= {m}-hold-until))']
        # Resume the original actual Dock target once, only if still a live
        # ally/self Dock. A cog already trading needs no intervention at all.
        add([*release, '(goal gl-row-found 1)', '(up-set-target-object search-local c: 0)',
             '(up-object-data object-data-action != actionid-trade)', f'(up-compare-goal {m}-target c:>= 0)'],[
            '(up-full-reset-search)', f'(up-add-object-by-id search-remote g: {m}-target)', '(set-goal gl-row-safe 0)'])
        for p in range(1,9):
            add([*release,'(goal gl-row-found 1)', '(up-set-target-object search-remote c: 0)',
                 '(up-object-data object-data-type == dock)', '(up-object-data object-data-status == status-ready)',
                 f'(up-object-data object-data-player == {p})', f'(or (stance-toward {p} ally) (up-object-data object-data-player == my-player-number))'],
                ['(set-goal gl-row-safe 1)'])
        add([*release,'(goal gl-row-found 1)', '(goal gl-row-safe 1)', '(up-set-target-object search-remote c: 0)'],[
            # Preserve the verified remote list while reacquiring exact local ID.
            '(up-reset-search 1 1 0 0)', f'(up-add-object-by-id search-local g: {m}-id)', *owner(),
            '(up-remove-objects search-local object-data-class != trade-cog-class)',
            '(up-remove-objects search-local object-data-action == actionid-trade)',
            '(up-target-objects 0 action-default -1 stance-no-attack)'])
        add(release,[f'(set-goal {m}-hold-until 0)', f'(set-goal {m}-target -1)',
            f'(up-modify-goal {m}-next g:= {m}-until)'])
        add(holding,[f'(up-modify-goal {m}-next g:= gl-row-clock)', f'(up-modify-goal {m}-next c:+ 8)'])
        add([f'(up-compare-goal {m}-id c:>= 0)',f'(up-compare-goal gl-row-clock g:>= {m}-until)'], [f'(set-goal {m}-id -1)'])
    holds=out[hold_start:]; del out[hold_start:]
    # Global clearance fairness: one hull at a time, rotating by ID. A moving
    # loaded/preparation/landing/recovery Transport outranks mission warships.
    add([*st(0),'(up-compare-goal gl-row-clock g:>= gl-row-next)'],[
        '(up-modify-goal gl-row-next g:= gl-row-clock)', '(up-modify-goal gl-row-next c:+ 8)',
        '(set-goal gl-row-stage 1)'])
    add([*st(1),'(up-compare-goal gl-row-hull c:< 0)'],[
        '(up-full-reset-search)', '(up-find-local c: transport-ship c: 40)',
        '(up-remove-objects search-local object-data-player != my-player-number)',
        '(up-remove-objects search-local object-data-move-x < 0)', '(up-remove-objects search-local object-data-move-y < 0)',
        '(up-remove-objects search-local object-data-id g:<= gl-row-cursor)',
        *[f'(up-remove-objects search-local object-data-id g:== gl-row-ban{i}-id)' for i in range(4)],
        '(up-clean-search search-local object-data-id search-order-asc)', '(set-goal gl-row-kind 1)', '(set-goal gl-row-stage 2)'])
    add([*st(2),'(not (up-set-target-object search-local c: 0))'],[
        '(up-full-reset-search)', '(up-find-local c: warship-class c: 40)',
        '(up-remove-objects search-local object-data-player != my-player-number)',
        '(up-remove-objects search-local object-data-group-flag < 0)',
        '(up-remove-objects search-local object-data-action != actionid-move)',
        '(up-remove-objects search-local object-data-id g:<= gl-row-cursor)',
        *[f'(up-remove-objects search-local object-data-id g:== gl-row-ban{i}-id)' for i in range(4)],
        '(up-clean-search search-local object-data-id search-order-asc)', '(set-goal gl-row-kind 2)'])
    add([*st(2),'(goal gl-row-kind 1)', '(up-set-target-object search-local c: 0)',
         '(up-object-data object-data-garrison-count <= 0)', '(up-object-data object-data-group-flag < 0)'],[
        '(up-get-object-data object-data-id gl-row-cursor)', '(set-goal gl-row-stage 0)'])
    add([*st(2),'(goal gl-row-kind 1)', '(up-set-target-object search-local c: 0)',f'(not {transport_intent})'],[
        '(up-get-object-data object-data-id gl-row-cursor)', '(set-goal gl-row-stage 0)'])
    add([*st(2),'(up-set-target-object search-local c: 0)'],[
        '(up-get-object-data object-data-id gl-row-hull)', '(set-goal gl-row-stalls 0)', '(set-goal gl-row-tries 0)',
        '(up-get-point position-object gl-row-last-x)',
        '(up-get-object-data object-data-move-x gl-row-old-dest-x)', '(up-get-object-data object-data-move-y gl-row-old-dest-y)',
        '(up-modify-goal gl-row-until g:= gl-row-clock)', '(up-modify-goal gl-row-until c:+ 120)', '(set-goal gl-row-stage 0)'])
    add(st(2),['(set-goal gl-row-cursor -1)', '(set-goal gl-row-stage 0)'])
    add([*st(1),'(up-compare-goal gl-row-hull c:>= 0)'],[*select('gl-row-hull'),
        '(up-remove-objects search-local object-data-player != my-player-number)',
        '(set-goal gl-row-stage 3)'])
    add([*st(3),'(not (up-set-target-object search-local c: 0))'],end())
    add([*st(3),'(goal gl-row-kind 1)', '(up-set-target-object search-local c: 0)',f'(not {transport_intent})'],end())
    add([*st(3),'(goal gl-row-kind 2)', '(up-set-target-object search-local c: 0)', '(up-object-data object-data-action != actionid-move)'],end())
    add([*st(3),'(goal gl-row-kind 1)', '(up-set-target-object search-local c: 0)',
         '(up-object-data object-data-garrison-count <= 0)', '(up-object-data object-data-group-flag < 0)'],end())
    add([*st(3),'(goal gl-row-kind 2)', '(up-set-target-object search-local c: 0)',
         '(up-object-data object-data-group-flag < 0)'],end())
    add([*st(3),'(up-compare-goal gl-row-clock g:>= gl-row-until)'],end())
    add([*st(3),'(up-set-target-object search-local c: 0)'],[
        '(up-get-point position-object gl-row-x)', '(up-get-object-data object-data-move-x gl-row-dest-x)',
        '(up-get-object-data object-data-move-y gl-row-dest-y)', '(up-get-object-data object-data-map-zone-id gl-row-zone)',
        '(up-get-point-distance gl-row-x gl-row-last-x gl-row-moved)',
        '(up-get-point-distance gl-row-dest-x gl-row-old-dest-x gl-row-turned)',
        '(up-get-point-distance gl-row-x gl-row-dest-x gl-row-distance)'])
    for condition in ('(up-compare-goal gl-row-moved c:> 2)', '(up-compare-goal gl-row-turned c:> 2)',
                      '(up-compare-goal gl-row-distance c:< 6)', '(up-compare-goal gl-row-dest-x c:< 0)', '(up-compare-goal gl-row-dest-y c:< 0)'):
        add([*st(3),condition],end())
    add(st(3),['(up-modify-goal gl-row-stalls c:+ 1)', '(up-copy-point gl-row-last-x gl-row-x)',
        '(up-copy-point gl-row-old-dest-x gl-row-dest-x)', '(set-goal gl-row-stage 4)'])
    # Hull progress/intent was remeasured above. Repair a due, overwritten hold
    # before consuming another one-at-a-time clearance attempt on a new merchant.
    out.extend(holds)
    add([*st(4),'(goal gl-row-issued 1)'],['(set-goal gl-row-stage 0)'])
    add([*st(4),'(up-compare-goal gl-row-stalls c:< 2)'],['(set-goal gl-row-stage 0)'])
    add([*st(4),'(up-compare-goal gl-row-tries c:>= 3)'],end())
    add(st(4),['(set-goal gl-row-found 0)'])
    for i in range(4):
        add([*st(4),f'(or (up-compare-goal gl-row-ban{i}-id c:< 0) (up-compare-goal gl-row-ban{i}-id g:== gl-row-hull))'],['(set-goal gl-row-found 1)'])
    add([*st(4),'(goal gl-row-found 0)'],end())
    add(st(4),['(set-goal gl-row-record -1)'])
    for i in range(3):
        add([*st(4),'(goal gl-row-record -1)',f'(up-compare-goal gl-row-m{i}-id c:< 0)'],[f'(set-goal gl-row-record {i})'])
    add([*st(4),'(goal gl-row-record -1)'],['(set-goal gl-row-stage 0)'])
    add(st(4),['(up-full-reset-search)', '(up-set-target-point gl-row-x)', '(up-filter-distance c: -1 c: 6)',
        '(up-find-local c: trade-cog-class c: 40)',*owner(), '(up-remove-objects search-local object-data-under-attack > 0)',
        '(up-remove-objects search-local object-data-map-zone-id g:!= gl-row-zone)',
        *[f'(up-remove-objects search-local object-data-id g:== gl-row-m{i}-id)' for i in range(3)],
        '(up-clean-search search-local object-data-distance search-order-asc)', '(set-goal gl-row-stage 5)'])
    add([*st(5),'(up-set-target-object search-local c: 0)'],[
        '(up-get-object-data object-data-id gl-row-merchant)', '(up-get-point position-object gl-row-merchant-x)',
        '(up-copy-point gl-row-hold-x gl-row-merchant-x)', '(up-cross-tiles gl-row-hold-x gl-row-dest-x c: 12)',
        '(set-goal gl-row-side 0)', '(set-goal gl-row-stage 6)'])
    add(st(5),end())
    # No intervening pass/search is assumed by a consumer. Validate bounds, zone,
    # the ACTUAL merchant's exact path, and local enemy military at the holding site.
    for side in range(2):
        check=[*st(6),f'(goal gl-row-side {side})']
        add(check,['(up-bound-point gl-row-bounded-x gl-row-hold-x)', '(up-get-point-zone gl-row-hold-x gl-row-count)',
            *select('gl-row-merchant')])
        for cond in ('(up-compare-goal gl-row-count g:!= gl-row-zone)',
                     '(up-compare-goal gl-row-hold-x g:!= gl-row-bounded-x)', '(up-compare-goal gl-row-hold-y g:!= gl-row-bounded-y)',
                     '(not (up-set-target-object search-local c: 0))'):
            add([*check,cond],['(set-goal gl-row-stage 7)'])
        add([*check,'(up-set-target-object search-local c: 0)', '(up-path-distance gl-row-hold-x 1 >= 32)'],['(set-goal gl-row-stage 7)'])
        add(check,['(up-modify-goal gl-row-focus s:= sn-focus-player-number)', '(set-goal gl-row-safe 1)'])
        for p in range(1,9):
            add([*check,f'(stance-toward {p} enemy)'],[
                f'(set-strategic-number sn-focus-player-number {p})', '(up-full-reset-search)',
                '(up-set-target-point gl-row-hold-x)', '(up-filter-distance c: -1 c: 14)',
                '(up-find-remote c: warship-class c: 40)', '(up-find-remote c: tower-class c: 40)',
                '(up-find-remote c: sea-tower c: 40)', '(up-find-remote c: town-center c: 40)',
                '(up-find-remote c: castle c: 40)', '(up-get-search-state local-total)'])
            add([*check,f'(stance-toward {p} enemy)', '(up-compare-goal remote-total c:> 0)'],['(set-goal gl-row-safe 0)'])
        add(check,['(up-modify-sn sn-focus-player-number g:= gl-row-focus)'])
        add([*check,'(goal gl-row-safe 0)'],['(set-goal gl-row-stage 7)'])
        add([*st(7),f'(goal gl-row-side {side})'],['(up-copy-point gl-row-hold-x gl-row-merchant-x)',
            '(up-cross-tiles gl-row-hold-x gl-row-dest-x c: -12)', '(set-goal gl-row-side 1)',
            f'(set-goal gl-row-stage {6 if side==0 else 0})'])
    for i in range(3):
        add([*st(6),f'(goal gl-row-record {i})'],[*select('gl-row-merchant'),*owner(),
            '(up-remove-objects search-local object-data-class != trade-cog-class)', '(up-remove-objects search-local object-data-under-attack > 0)',
            '(up-remove-objects search-local object-data-map-zone-id g:!= gl-row-zone)', '(set-goal gl-row-stage 8)'])
        add([*st(8),f'(goal gl-row-record {i})','(up-set-target-object search-local c: 0)'],[
            f'(up-get-object-data object-data-target-id gl-row-m{i}-target)',
            f'(up-modify-goal gl-row-m{i}-id g:= gl-row-merchant)', f'(up-copy-point gl-row-m{i}-x gl-row-hold-x)',
            f'(up-modify-goal gl-row-m{i}-zone g:= gl-row-zone)', f'(up-modify-goal gl-row-m{i}-until g:= gl-row-clock)',
            f'(up-modify-goal gl-row-m{i}-until c:+ 120)', f'(up-modify-goal gl-row-m{i}-hold-until g:= gl-row-clock)',
            f'(up-modify-goal gl-row-m{i}-hold-until c:+ 32)', f'(up-modify-goal gl-row-m{i}-next g:= gl-row-clock)',
            f'(up-modify-goal gl-row-m{i}-next c:+ 8)', f'(set-goal gl-row-m{i}-renewals 0)',
            *owner(), '(up-target-point gl-row-hold-x action-move -1 stance-no-attack)',
            '(up-modify-goal gl-row-tries c:+ 1)', '(set-goal gl-row-active 1)', '(set-goal gl-row-issued 1)',
            '(up-chat-data-to-all str-t12-diag-id c: 420)', '(up-chat-data-to-all str-t12-diag-value g: gl-row-merchant)',
            '(up-chat-data-to-all str-t12-diag-id c: 421)', '(up-chat-data-to-all str-t12-diag-value g: gl-row-hull)',
            '(set-goal gl-row-stage 9)'])
    # A successful intervention consumes the hull's 180s cooldown record. The
    # same observed hull may receive at most 3 sequential interventions before
    # release; progress or intent change releases earlier. No timer extensions.
    add(st(9),['(set-goal gl-row-found 0)'])
    for i in range(4):
        add([*st(9),f'(up-compare-goal gl-row-ban{i}-id g:== gl-row-hull)'],['(set-goal gl-row-found 1)'])
    for i in range(4):
        add([*st(9),'(goal gl-row-found 0)',f'(up-compare-goal gl-row-ban{i}-id c:< 0)'],[
            f'(up-modify-goal gl-row-ban{i}-id g:= gl-row-hull)',f'(up-modify-goal gl-row-ban{i}-until g:= gl-row-clock)',
            f'(up-modify-goal gl-row-ban{i}-until c:+ 180)','(set-goal gl-row-found 1)'])
    add(st(9),['(set-goal gl-row-stage 0)'])
    add(st(8),['(set-goal gl-row-stage 0)'])
    return '\n\n'.join(out)+'\n'


def outputs(): return {'rawai-naval-row-defs.per':definitions(), 'rawai-naval-right-of-way.per':generate()}


if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--write',action='store_true');args=parser.parse_args()
    for name,text in outputs().items():
        path=ROOT/name
        if args.write:path.write_text(text,encoding='utf-8')
        elif not path.exists() or path.read_text(encoding='utf-8-sig')!=text:raise SystemExit(f'stale: {name}')
