"""Three independent post-screening assault records; emit apply_patch, never deploy.

One existing preparation lane feeds three concurrent voyages. The finite DUC
table has only groups 0/18/19 free: each owns its hull, manifest and screen.
Timers are game-time deadlines in each record, not aliased engine timer slots.
"""
from pathlib import Path
import argparse
import difflib
from generate_assault_plans import outputs as plan_outputs, seed_rules

ROOT = Path(__file__).resolve().parents[1]
GROUPS = (0, 18, 19)
FIELDS = ('state', 'hull', 'enemy', 'cargo', 'screen', 'origin-x', 'origin-y',
          'waypoint-x', 'waypoint-y', 'landing-x', 'landing-y', 'target-x', 'target-y',
          'target-zone', 'next', 'progress-until', 'travel-until', 'best', 'distance',
          'hp', 'previous-hp', 'attacker', 'issue', 'reason', 'sample', 'zone',
          'x', 'y', 'clear-count', 'clear-x', 'clear-y', 'water-zone', 'unscreened', 'stalls',
          'combat-until', 'combat-target', 'combat-last', 'combat-tries', 'combat-failed', 'combat-misses')

# Diagnostic-only: keep legacy bypass denial 4, qualify the failing predicate.
# "Not in game" does not distinguish resignation, defeat or disconnection.
DENIAL_DETAILS = {
    401: ('initial enemy scan cursor invalid', 'gl-assault-fallback-player'),
    402: ('next enemy scan cursor invalid', 'gl-assault-fallback-player'),
    411: ('checked enemy below player range', 'gl-assault-diag-checked-enemy'),
    412: ('checked enemy above player range', 'gl-assault-diag-checked-enemy'),
    413: ('checked enemy not in game', 'gl-assault-diag-checked-enemy'),
    414: ('checked enemy in game but not hostile', 'gl-assault-diag-checked-enemy'),
    415: ('checked/saved enemy mismatch', 'gl-assault-diag-checked-enemy'),
    419: ('live flag rejects passing snapshot', 'gl-assault-preflight-live'),
}


def rule(facts, actions):
    return '(defrule\n\t' + '\n\t'.join(facts) + '\n=>\n\t' + '\n\t'.join(actions) + '\n)'


def definitions():
    out = [';Generated by tools/generate_assault_missions.py; records never alias.']
    for i, group in enumerate(GROUPS, 1):
        out.append(f'(defconst assault-mission-{i}-group {group})')
        out.extend(f'(defconst gl-am{i}-{key} {14500 + i * 100 + j})'
                   for j, key in enumerate(FIELDS))
    out += ['(defconst gl-assault-admission-open 14900)',
            '(defconst gl-assault-preflight-live 14901)',
            '(defconst gl-assault-mission-clock 14902)',
            '(defconst gl-assault-mission-focus 14903)',
            '(defconst gl-assault-diag-checked-enemy 14904)',
            '(defconst gl-assault-diag-enemy-failure 14905)',
            '(defconst gl-assault-diag-subcode 14906)',
            '(defconst gl-assault-diag-global-target 14907)',
            '(defconst gl-assault-diag-previous-enemy 14908)',
            '(defconst gl-transport-preparation-owned 14909)',
            '(defconst gl-assault-fallback-hostile 14910)',
            '(defconst gl-assault-recovery-until 14911)',
            '(defconst gl-assault-recovery-rejected 14912)',
            '(defconst gl-assault-recovery-retry 14913)',
            '(defconst gl-assault-admission-objective 14914)',
            '(defconst gl-assault-rendezvous-x 14915)',
            '(defconst gl-assault-rendezvous-y 14916)',
            '(defconst gl-assault-rendezvous-until 14917)',
            '(defconst gl-assault-rendezvous-next 14918)',
            '(defconst gl-migration-rendezvous-x 14919)',
            '(defconst gl-migration-rendezvous-y 14920)',
            '(defconst gl-migration-rendezvous-until 14921)',
            '(defconst gl-migration-rendezvous-next 14922)',
            '(defconst gl-assault-admission-diag-next 14923)',
            '(defconst gl-assault-admission-diag-state 14924)',
            '(defconst gl-assault-admission-diag-mask 14925)',
            '(defconst gl-assault-admission-last-stage 14926)',
            '(defconst gl-assault-admission-last-time 14927)',
            '(defconst gl-assault-admission-reported-mask 14928)',
            '(defconst gl-assault-admission-reported-stage 14929)',
            '(defconst str-assault-slot "RAW3 slot: %d")',
            '(defconst str-assault-hull "RAW3 hull: %d")',
            '(defconst str-assault-event "RAW3 event: %d")',
            '(defconst str-assault-saved-enemy "RAW assault saved enemy: %d")']
    labels = {'stage': 'stage (1 load-ready, 2 bypass)', 'subcode': 'subcode',
              'hull': 'hull', 'global-target': 'global target', 'checked-enemy': 'checked enemy',
              'enemy-failure': 'checked enemy failure', 'live': 'live gate',
              'iterator': 'iterator player', 'first': 'iterator first',
              'previous': 'iterator previous', 'seen': 'enemies scanned'}
    out.extend(f'(defconst str-assault-deny-{key} "RAW44T cancellation {label}: %d")'
               for key, label in labels.items())
    out.extend(f'(defconst str-assault-deny-{code} "RAW44T deny {code}: {message}: %d")'
               for code, (message, _) in DENIAL_DETAILS.items())
    out.append('(load "rawai-transport-unload")')
    return '\n'.join(out) + '\n'


def cancellation_details(facts, stage):
    """A same-pass terminal report. Never alters searches, orders or policy state."""
    detail = 'gl-assault-diag-subcode'
    out = []
    if stage == 1:
        out.append(rule(facts, [f'(up-modify-goal {detail} g:= gl-assault-diag-enemy-failure)']))
    else:
        out.append(rule([*facts, f'(goal {detail} 401)',
                         '(up-compare-goal gl-assault-fallback-seen c:> 0)'],
                        [f'(set-goal {detail} 402)']))
    out.append(rule([*facts, f'(goal {detail} 0)'], [f'(set-goal {detail} 419)']))
    # Do not blame the current manifest's player for a check of another player.
    # Still print the sampled failure (413/414/etc.) separately for attribution.
    out.append(rule([*facts, f'(up-compare-goal {detail} c:>= 411)',
        '(up-compare-goal gl-assault-diag-checked-enemy g:!= gl-assault-manifest-player)'],
        [f'(set-goal {detail} 415)']))
    out.append(rule(facts, [
        '(up-modify-goal gl-assault-diag-global-target s:= sn-target-player-number)',
        f'(up-chat-data-to-all str-assault-deny-stage c: {stage})',
        f'(up-chat-data-to-all str-assault-deny-subcode g: {detail})',
        '(up-chat-data-to-all str-assault-deny-hull g: gl-transport-route-id)',
        '(up-chat-data-to-all str-assault-saved-enemy g: gl-assault-manifest-player)',
        '(up-chat-data-to-all str-assault-deny-global-target g: gl-assault-diag-global-target)',
        '(up-chat-data-to-all str-assault-deny-checked-enemy g: gl-assault-diag-checked-enemy)',
        '(up-chat-data-to-all str-assault-deny-enemy-failure g: gl-assault-diag-enemy-failure)',
        '(up-chat-data-to-all str-assault-deny-live g: gl-assault-preflight-live)']))
    if stage == 2:
        out.append(rule([*facts, f'(up-compare-goal {detail} c:< 410)'], [
            '(up-chat-data-to-all str-assault-deny-iterator g: gl-assault-fallback-player)',
            '(up-chat-data-to-all str-assault-deny-first g: gl-assault-fallback-first)',
            '(up-chat-data-to-all str-assault-deny-previous g: gl-assault-diag-previous-enemy)',
            '(up-chat-data-to-all str-assault-deny-seen g: gl-assault-fallback-seen)']))
    for code, (_, goal) in DENIAL_DETAILS.items():
        out.append(rule([*facts, f'(goal {detail} {code})'],
                        [f'(up-chat-data-to-all str-assault-deny-{code} g: {goal})']))
    return '\n\n'.join(out)


def admission():
    out = [';State:0 FREE,1 WAYPOINT,2 LANDING,3 RETURN,4 QUARANTINE,5 RELEASE,6 LANDED COMBAT.',
           ';Event:0 commit,1 enemy left,2 hostile fire,3 invalid landing,',
           ';4 no progress,5 voyage deadline,6 hull lost,7 empty before landing,',
           ';8 landed,9 return empty,10 quarantine,11 obstruction clearance,12 combat release,13 combat target.']
    for i in range(1, 4):
        out.append(rule(['(true)'], [f'(set-goal gl-am{i}-state 0)',
            f'(set-goal gl-am{i}-hull -1)', '(disable-self)']))
    out.append(rule(['(true)'], [
        '(set-goal gl-assault-admission-diag-next 0)',
        '(set-goal gl-assault-admission-diag-state 0)',
        '(set-goal gl-assault-admission-diag-mask 0)',
        '(set-goal gl-assault-admission-last-stage 0)',
        '(set-goal gl-assault-admission-last-time 0)',
        '(set-goal gl-assault-admission-reported-mask -1)',
        '(set-goal gl-assault-admission-reported-stage -1)',
        '(disable-self)']))
    out.append(rule(['(true)'], ['(up-get-fact game-time 0 gl-assault-mission-clock)',
        '(set-goal gl-assault-admission-open NO)', '(set-goal gl-assault-preflight-live NO)',
        '(up-modify-goal gl-assault-diag-checked-enemy g:= gl-assault-manifest-player)',
        '(set-goal gl-assault-diag-enemy-failure 411)']))
    out.append(rule(['(or (goal gl-am1-state 0) (or (goal gl-am2-state 0) (goal gl-am3-state 0)))'],
                    ['(set-goal gl-assault-admission-open YES)']))
    # Literal player predicates avoid mutable target-player/focus-player aliases.
    # Record which predicate failed in this very snapshot, not a later recheck.
    out.append(rule(['(up-compare-goal gl-assault-manifest-player c:> 8)'],
                    ['(set-goal gl-assault-diag-enemy-failure 412)']))
    for p in range(1, 9):
        out.append(rule([f'(goal gl-assault-manifest-player {p})', f'(not (player-in-game {p}))'],
                        ['(set-goal gl-assault-diag-enemy-failure 413)']))
        out.append(rule([f'(goal gl-assault-manifest-player {p})', f'(player-in-game {p})',
                         f'(not (stance-toward {p} enemy))'],
                        ['(set-goal gl-assault-diag-enemy-failure 414)']))
        out.append(rule([f'(goal gl-assault-manifest-player {p})', f'(player-in-game {p})',
                         f'(stance-toward {p} enemy)'],
                        ['(set-goal gl-assault-preflight-live YES)',
                         '(set-goal gl-assault-diag-enemy-failure 0)']))
    out.append(cancellation_details(['(goal gl-transport-route-state TRANSPORT-ROUTE-LOAD-READY)',
                                     '(goal gl-assault-preflight-live NO)'], 1))
    out.append(seed_rules())
    out.append(rule(['(up-compare-goal gl-assault-mission-clock g:>= gl-assault-recovery-retry)'],
                    ['(set-goal gl-assault-recovery-rejected -1)']))
    return '\n\n'.join(out) + '\n'


def missions():
    out = [';Generated three-slot voyage controller. Never reads global target or home-defense state.',
           ';Shared search lists are reconstructed inside each uninterrupted sample; only goals/groups persist.',
           ';A native/manual transport already underway is NOT adopted by this controller.']
    out.append(rule(['(true)'], ['(up-get-fact game-time 0 gl-assault-mission-clock)',
        '(up-modify-goal gl-assault-mission-focus s:= sn-focus-player-number)']))
    for i, _ in enumerate(GROUPS, 1):
        g = f'assault-mission-{i}-group'
        def v(key): return f'gl-am{i}-{key}'
        def setv(key, value): return f'(set-goal {v(key)} {value})'
        def copy(key, source): return f'(up-modify-goal {v(key)} g:= {source})'
        def deadline(key, seconds):
            return [copy(key, 'gl-assault-mission-clock'), f'(up-modify-goal {v(key)} c:+ {seconds})']
        def select():
            return ['(up-full-reset-search)', f'(up-add-object-by-id search-local g: {v("hull")})',
                    '(up-remove-objects search-local object-data-player != my-player-number)',
                    f'(up-remove-objects search-local object-data-group-flag != {g})']
        def command(point, action):
            return [*select(), f'(up-target-point {v(point)} {action} -1 stance-no-attack)']
        def log(event):
            return [f'(up-chat-data-to-all str-assault-slot c: {i})',
                    f'(up-chat-data-to-all str-assault-hull g: {v("hull")})',
                    f'(up-chat-data-to-all str-assault-saved-enemy g: {v("enemy")})',
                    f'(up-chat-data-to-all str-assault-event c: {event})']
        def recover(reason):
            return [setv('state', 3), setv('issue', 1), setv('reason', reason),
                    *deadline('travel-until', 180), *log(reason)]
        active = [f'(up-compare-goal {v("state")} c:>= 1)', f'(up-compare-goal {v("state")} c:<= 4)']
        sample = [f'(goal {v("sample")} YES)']

        out.append(rule(['(goal gl-transport-route-state TRANSPORT-ROUTE-DEPARTURE-START)'], [
            '(up-full-reset-search)', '(up-add-object-by-id search-local g: gl-transport-route-id)',
            '(up-remove-objects search-local object-data-player != my-player-number)',
            '(up-remove-objects search-local object-data-group-flag != attack-transport-group)']))

        # Transfer only after the existing full/partial acceptance and screening.
        # Setting route state to 101 makes allocation exclusive even with 3 free slots.
        out.append(rule(['(goal gl-transport-route-state TRANSPORT-ROUTE-DEPARTURE-START)',
                         f'(goal {v("state")} 0)', '(goal gl-assault-preflight-live YES)',
                         '(up-compare-goal gl-assault-manifest-hull g:== gl-transport-route-id)',
                         '(up-compare-goal gl-assault-manifest-count c:>= 5)',
                         '(up-set-target-object search-local c: 0)',
                         '(up-object-data object-data-garrison-count g:>= gl-assault-manifest-count)'], [
            '(set-goal gl-transport-route-state 101)', setv('state', 11),
            copy('hull', 'gl-transport-route-id'), copy('enemy', 'gl-assault-manifest-player'),
            copy('cargo', 'gl-assault-manifest-count'), copy('screen', 'gl-transport-screen-id'),
            copy('target-zone', 'gl-transport-route-target-zone'),
            copy('unscreened', 'gl-assault-fallback-deadline'), setv('reason', 0),
            setv('clear-count', 0), setv('stalls', 0), setv('issue', 1), setv('best', 99999),
            *[f'(up-bound-point {v(key)} gl-transport-route-{key})'
              for key in ('origin-x', 'waypoint-x', 'landing-x', 'target-x')]]))
        out.append(rule([f'(goal {v("state")} 11)'], [
            '(up-full-reset-search)', f'(up-add-object-by-id search-local g: {v("screen")})',
            '(up-remove-objects search-local object-data-player != my-player-number)',
            '(up-remove-objects search-local object-data-group-flag != transport-screen-group)']))
        out.append(rule([f'(goal {v("state")} 11)', '(not (up-set-target-object search-local c: 0))'],
                        [setv('screen', -1)]))
        out.append(rule([f'(goal {v("state")} 11)'], [
            '(up-full-reset-search)', '(up-set-group search-local c: attack-boarding-group)',
            '(up-remove-objects search-local object-data-player != my-player-number)',
            '(up-remove-objects search-local object-data-group-flag != attack-boarding-group)',
            # Preserve all accepted manifest members, including late arrivals; do not
            # issue orders to passengers until the hull is confirmed empty ashore.
            f'(up-add-object-by-id search-local g: {v("hull")})',
            f'(up-add-object-by-id search-local g: {v("screen")})',
            '(up-remove-objects search-local object-data-player != my-player-number)',
            f'(up-create-group 0 0 c: {g})',
            '(up-modify-group-flag 0 c: attack-boarding-group)',
            '(up-reset-group c: attack-boarding-group)',
            '(up-modify-group-flag 0 c: attack-transport-group)',
            '(up-reset-group c: attack-transport-group)',
            '(up-modify-group-flag 0 c: transport-screen-group)',
            '(up-reset-group c: transport-screen-group)',
            f'(up-modify-group-flag 1 c: {g})', setv('state', 12)]))
        out.append(rule([f'(goal {v("state")} 12)'], [
            *select(), setv('previous-hp', 0), setv('next', 0),
            *deadline('travel-until', 600), *deadline('progress-until', 90),
            setv('state', 1), '(set-goal gl-transport-route-state TRANSPORT-ROUTE-IDLE)',
            '(set-goal gl-transport-route-script-load NO)', '(set-goal gl-transport-route-id -1)',
            '(set-goal gl-transport-screen-id -1)', '(set-goal gl-assault-fallback-deadline 0)',
            '(set-goal gl-assault-fallback-progress-deadline 0)',
            '(up-set-timer c: t-transport-route c: 1)', *log(0)]))
        out.append(rule([f'(goal {v("state")} 1)', f'(up-compare-goal {v("unscreened")} c:> 0)'],
                        [copy('travel-until', v('unscreened')), setv('unscreened', 0)]))

        # Each sample reconstructs its exact ship; no shared search survives a pass.
        out.append(rule(['(true)'], [setv('sample', 0)]))
        out.append(rule([*active, f'(up-compare-goal gl-assault-mission-clock g:>= {v("next")})'], [
            setv('sample', 1), *deadline('next', 8), *select()]))
        out.append(rule([*sample, '(not (up-set-target-object search-local c: 0))'],
                        [setv('state', 5), setv('reason', 6), *log(6)]))
        out.append(rule([*sample, *active, '(up-set-target-object search-local c: 0)'], [
            f'(up-get-object-data object-data-garrison-count {v("cargo")})',
            f'(up-get-object-data object-data-hitpoints {v("hp")})',
            f'(up-get-object-data object-data-attacker-id {v("attacker")})',
            f'(up-get-object-data object-data-map-zone-id {v("water-zone")})',
            f'(up-get-point position-object {v("x")})']))
        # Sample the owned leg BEFORE policy cancellation. A completed landing
        # must retain its passenger handoff even if a watchdog expires this tick.
        for state, point in ((1, 'waypoint-x'), (2, 'landing-x'), (3, 'origin-x'), (4, 'origin-x')):
            out.append(rule([*sample, f'(goal {v("state")} {state})'], [*select(), f'(up-set-target-point {v(point)})']))
        out.append(rule([*sample, *active, '(up-set-target-object search-local c: 0)'], [
            f'(up-get-object-data object-data-distance {v("distance")})']))
        # Completion is physical cargo-empty near the accepted same-island beach.
        out.append(rule([*sample, f'(goal {v("state")} 2)', f'(up-compare-goal {v("cargo")} c:<= 0)',
                         f'(up-compare-goal {v("distance")} c:<= 12)'], [
            *command('origin-x', 'action-move'), setv('state', 14)]))
        out.append(rule([f'(goal {v("state")} 14)'], [
            '(up-full-reset-search)', f'(up-set-group search-local c: {g})',
            '(up-remove-objects search-local object-data-player != my-player-number)',
            f'(up-remove-objects search-local object-data-group-flag != {g})',
            f'(up-create-group 0 0 c: {g})', f'(up-modify-group-flag 0 c: {g})',
            f'(up-remove-objects search-local object-data-id g:== {v("hull")})',
            f'(up-remove-objects search-local object-data-id g:== {v("screen")})',
            '(up-remove-objects search-local object-data-garrisoned == 1)',
            f'(up-remove-objects search-local object-data-map-zone-id g:!= {v("target-zone")})',
            f'(up-create-group 0 0 c: {g})', f'(up-modify-group-flag 1 c: {g})',
            f'(up-target-point {v("target-x")} action-default -1 stance-aggressive)',
            setv('state', 6), setv('reason', 8), *deadline('combat-until', 300),
            setv('combat-last', -1), setv('combat-failed', -1),
            setv('combat-tries', 0), setv('combat-misses', 0), *log(8)]))
        outbound = [f'(or (goal {v("state")} 1) (goal {v("state")} 2))']
        for p in range(1, 9):
            out.append(rule([*sample, *outbound, f'(goal {v("enemy")} {p})',
                             f'(not (player-in-game {p}))'], recover(1)))
        # Under-attack alone is NOT an emergency: friendly-fire events must not recall.
        out.append(rule([*sample, *outbound, f'(up-compare-goal {v("previous-hp")} c:> 0)',
                         f'(up-compare-goal {v("hp")} g:< {v("previous-hp")})'], [
            '(up-full-reset-search)', f'(up-add-object-by-id search-remote g: {v("attacker")})']))
        for p in range(1, 9):
            out.append(rule([*sample, *outbound, f'(up-compare-goal {v("previous-hp")} c:> 0)',
                f'(up-compare-goal {v("hp")} g:< {v("previous-hp")})', f'(stance-toward {p} enemy)',
                '(up-set-target-object search-remote c: 0)', f'(up-object-data object-data-player == {p})'], recover(2)))
        out.append(rule([*sample, *active], [copy('previous-hp', v('hp'))]))
        out.append(rule([*sample, *outbound, f'(up-compare-goal gl-assault-mission-clock g:>= {v("travel-until")})'], recover(5)))

        out.append(rule([*sample, *outbound, f'(up-compare-goal {v("distance")} g:< {v("best")})'], [
            copy('best', v('distance')), f'(up-modify-goal {v("best")} c:- 2)',
            setv('stalls', 0), *deadline('progress-until', 90)]))
        out.append(rule([*sample, f'(goal {v("state")} 1)',
                         f'(up-compare-goal {v("distance")} g:> {v("best")})'],
                        [f'(up-modify-goal {v("stalls")} c:+ 1)']))
        out.append(rule([*sample, f'(goal {v("state")} 1)', f'(up-compare-goal {v("cargo")} c:<= 0)'],
                        [setv('state', 5), setv('reason', 7), *log(7)]))
        out.append(rule([*sample, *outbound, f'(up-compare-goal gl-assault-mission-clock g:>= {v("progress-until")})'], recover(4)))
        out.append(rule([*sample, f'(goal {v("state")} 1)', f'(up-compare-goal {v("distance")} c:<= 8)'], [
            f'(up-get-point-zone {v("landing-x")} {v("zone")})', setv('state', 13)]))
        out.append(rule([f'(goal {v("state")} 13)',
            f'(or (up-compare-goal {v("target-zone")} c:< 0) (up-compare-goal {v("zone")} g:!= {v("target-zone")}))'], recover(3)))
        out.append(rule([f'(goal {v("state")} 13)'], [
            # Stage only escorts currently guarding this exact hull; the
            # periodic guard selector pauses while ANY slot is landing.
            '(up-full-reset-search)', '(up-set-group search-local c: transport-escort-group)',
            '(up-remove-objects search-local object-data-player != my-player-number)',
            '(up-remove-objects search-local object-data-group-flag != transport-escort-group)',
            f'(up-remove-objects search-local object-data-target-id g:!= {v("hull")})',
            f'(up-bound-point {v("clear-x")} {v("landing-x")})',
            f'(up-cross-tiles {v("clear-x")} {v("waypoint-x")} c: -18)',
            f'(up-target-point {v("clear-x")} action-move -1 stance-aggressive)']))
        out.append(rule([f'(goal {v("state")} 13)'], [
            # Exact screen only. Never stage another mission's escort group.
            '(up-full-reset-search)', f'(up-add-object-by-id search-local g: {v("screen")})',
            '(up-remove-objects search-local object-data-player != my-player-number)',
            f'(up-remove-objects search-local object-data-group-flag != {g})',
            f'(up-bound-point {v("clear-x")} {v("landing-x")})',
            f'(up-cross-tiles {v("clear-x")} {v("waypoint-x")} c: 18)',
            f'(up-target-point {v("clear-x")} action-move -1 stance-no-attack)',
            # Distances from different legs are not comparable. Without this
            # reset, reaching the waypoint at 0-8 tiles makes all subsequent
            # movement toward a more distant beach fail the progress test.
            # The next eight-second sample establishes the landing baseline;
            # neither the private objective nor the total voyage budget changes.
            setv('state', 2), setv('best', 99999), setv('stalls', 0),
            setv('issue', 1), *deadline('progress-until', 60)]))
        out.append(rule([*sample, f'(or (goal {v("state")} 3) (goal {v("state")} 4))',
                         f'(up-compare-goal {v("cargo")} c:<= 0)'],
                        [setv('state', 5), setv('reason', 9), *log(9)]))
        out.append(rule([*sample, f'(goal {v("state")} 3)',
                         f'(up-compare-goal gl-assault-mission-clock g:>= {v("travel-until")})'], [
            setv('state', 4), setv('issue', 0), *deadline('next', 30), *log(10)]))

        # Bounded departure clearance. Only idle, empty, FREE ships in the same
        # water zone can yield. An active mission is never a movable blocker.
        out.append(rule([*sample, f'(goal {v("state")} 1)', f'(up-compare-goal {v("clear-count")} c:< 3)',
            f'(up-compare-goal {v("stalls")} c:>= 3)',
            f'(up-compare-goal {v("distance")} g:> {v("best")})'], [
            *select(), f'(up-set-target-point {v("origin-x")})']))
        out.append(rule([*sample, f'(goal {v("state")} 1)', f'(up-compare-goal {v("clear-count")} c:< 3)',
            f'(up-compare-goal {v("stalls")} c:>= 3)',
            f'(up-compare-goal {v("distance")} g:> {v("best")})',
            '(up-set-target-object search-local c: 0)', '(up-object-data object-data-distance <= 20)',
            '(up-object-data object-data-idling == 1)'], [
            '(up-full-reset-search)', f'(up-set-target-point {v("x")})', '(up-filter-distance c: 28 c: 200)',
            '(up-find-local c: transport-ship c: 40)', '(up-find-local c: trade-cog-class c: 20)',
            '(up-find-local c: warship-class c: 40)',
            f'(up-remove-objects search-local object-data-map-zone-id g:!= {v("water-zone")})',
            '(up-clean-search search-local object-data-distance search-order-asc)', setv('sample', 2)]))
        out.append(rule([f'(goal {v("sample")} 2)', '(up-set-target-object search-local c: 0)'], [
            f'(up-get-point position-object {v("clear-x")})', '(up-full-reset-search)',
            f'(up-set-target-point {v("x")})', '(up-filter-distance c: -1 c: 12)',
            '(up-find-local c: transport-ship c: 20)', '(up-find-local c: trade-cog-class c: 20)',
            '(up-find-local c: warship-class c: 20)',
            '(up-remove-objects search-local object-data-player != my-player-number)',
            '(up-remove-objects search-local object-data-group-flag >= 0)',
            '(up-remove-objects search-local object-data-garrison-count > 0)',
            '(up-remove-objects search-local object-data-idling != 1)',
            '(up-remove-objects search-local object-data-under-attack > 0)',
            '(up-remove-objects search-local object-data-order == orderid-transport)',
            '(up-remove-objects search-local object-data-order == orderid-unload)',
            f'(up-remove-objects search-local object-data-map-zone-id g:!= {v("water-zone")})',
            '(up-clean-search search-local object-data-distance search-order-asc)',
            '(up-remove-objects search-local object-data-index > 0)', setv('sample', 3)]))
        out.append(rule([f'(goal {v("sample")} 3)', '(up-set-target-object search-local c: 0)'], [
            '(up-remove-objects search-local object-data-player != my-player-number)',
            '(up-remove-objects search-local object-data-group-flag >= 0)',
            f'(up-target-point {v("clear-x")} action-move -1 stance-no-attack)',
            f'(up-modify-goal {v("clear-count")} c:+ 1)', setv('stalls', 0), setv('issue', 1), *log(11)]))

        # Do not repeat commands while meaningful movement continues. Retry only
        # an idle hull at the eight-second sample cadence, not every rule sweep.
        out.append(rule([*sample, f'(up-compare-goal {v("state")} c:>= 1)',
                         f'(up-compare-goal {v("state")} c:<= 3)'], select()))
        out.append(rule([*sample, f'(up-compare-goal {v("state")} c:>= 1)',
            f'(up-compare-goal {v("state")} c:<= 3)', '(up-set-target-object search-local c: 0)',
            '(up-object-data object-data-idling == 1)'], [setv('issue', 1)]))
        for state, point, action in ((1, 'waypoint-x', 'action-move'), (2, 'landing-x', 'action-unload'),
                                     (3, 'origin-x', 'action-unload')):
            out.append(rule([f'(goal {v("state")} {state})', f'(goal {v("issue")} 1)'],
                            [*command(point, action), setv('issue', 0)]))
        # A quarantined loaded hull retains ownership but receives no command
        # loop. Manual recovery, emptying, destruction or conversion releases it.
        # Retain the exact landed manifest, NOT the now-empty hull or screen.
        # No global attack-readiness/target gate and no recruitment of free troops.
        # Combat consumes this mission slot for at most 300s; release never STOPs
        # a continuing attack. This keeps the finite three-group ownership bound.
        def members():
            return ['(up-full-reset-search)', f'(up-set-group search-local c: {g})',
                    '(up-remove-objects search-local object-data-player != my-player-number)',
                    f'(up-remove-objects search-local object-data-group-flag != {g})']
        combat = [f'(goal {v("state")} 6)', f'(goal {v("sample")} 6)']
        out.append(rule([f'(goal {v("state")} 6)',
                         f'(up-compare-goal gl-assault-mission-clock g:>= {v("next")})'], [
            setv('sample', 6), *deadline('next', 16), *members(),
            f'(up-create-group 0 0 c: {g})']))
        out.append(rule([*combat, f'(or (up-group-size c: {g} <= 0)\n'
                         f'\t(up-compare-goal gl-assault-mission-clock g:>= {v("combat-until")}))'],
                        [setv('state', 5), setv('reason', 12), *log(12)]))
        out.append(rule(combat, [*members(),
            '(up-remove-objects search-local object-data-garrisoned == 1)',
            f'(up-remove-objects search-local object-data-map-zone-id g:!= {v("target-zone")})',
            setv('combat-target', -1)]))
        out.append(rule([*combat, '(up-set-target-object search-local c: 0)'], [
            f'(up-get-point position-object {v("x")})', setv('sample', 7)]))
        seeking = [f'(goal {v("state")} 6)', f'(goal {v("sample")} 7)']
        # Prefer the sealed opponent, then another living hostile on this landmass.
        for mode, player in [('g:=', v('enemy')), *[('c:=', str(p)) for p in range(1, 9)]]:
            search = [*seeking, f'(goal {v("combat-target")} -1)']
            out.append(rule(search, [f'(up-modify-sn sn-focus-player-number {mode} {player})']))
            hostile = [*search, '(player-in-game focus-player)', '(stance-toward focus-player enemy)']
            out.append(rule(hostile, ['(up-full-reset-search)',
                f'(up-set-target-point {v("x")})', '(up-filter-distance c: -1 c: 255)',
                '(up-find-remote c: scout-cavalry-class c: 40)',
                '(up-find-remote c: cavalry-archer-class c: 40)',
                '(up-find-remote c: cavalry-class c: 40)',
                '(up-find-remote c: infantry-class c: 40)',
                '(up-find-remote c: archery-class c: 40)',
                '(up-find-remote c: siege-weapon-class c: 40)',
                '(up-find-remote c: tower-class c: 40)',
                '(up-find-remote c: building-class c: 40)',
                '(up-find-remote c: villager-class c: 40)',
                '(up-remove-objects search-remote object-data-player != focus-player)',
                '(up-remove-objects search-remote object-data-hitpoints <= 0)',
                f'(up-remove-objects search-remote object-data-map-zone-id g:!= {v("target-zone")})',
                f'(up-remove-objects search-remote object-data-id g:== {v("combat-failed")})',
                '(up-clean-search search-remote object-data-distance search-order-asc)']))
            out.append(rule([*hostile, '(up-set-target-object search-remote c: 0)'], [
                f'(up-get-object-data object-data-id {v("combat-target")})']))
        found = [*seeking, f'(up-compare-goal {v("combat-target")} c:>= 0)']
        out.append(rule([*found, f'(up-compare-goal {v("combat-target")} g:!= {v("combat-last")})'], [
            setv('combat-tries', 0), *log(13),
            f'(up-chat-data-to-all "RAW landed combat target: %d" g: {v("combat-target")})']))
        # Close the logical combat sample in persistent PER state as part of the
        # command action. Do not depend on object-data-action becoming visible
        # before another evaluation can observe that this sample already issued.
        out.append(rule(found, [*members(),
            '(up-remove-objects search-local object-data-garrisoned == 1)',
            f'(up-remove-objects search-local object-data-map-zone-id g:!= {v("target-zone")})',
            '(up-remove-objects search-local object-data-action == actionid-attack)',
            f'(up-add-object-by-id search-remote g: {v("combat-target")})',
            '(up-target-objects 1 action-default -1 stance-aggressive)',
            copy('combat-last', v('combat-target')), setv('combat-misses', 0),
            f'(up-modify-goal {v("combat-tries")} c:+ 1)', setv('sample', 10)]))
        # The post-issue state preserves third-try failed-target exclusion while
        # keeping the command rule itself immediately ineligible.
        out.append(rule([f'(goal {v("state")} 6)', f'(goal {v("sample")} 10)',
                         f'(up-compare-goal {v("combat-target")} c:>= 0)',
                         f'(up-compare-goal {v("combat-tries")} c:>= 3)'],
                        [copy('combat-failed', v('combat-target'))]))
        out.append(rule([*seeking, f'(goal {v("combat-target")} -1)'],
                        [f'(up-modify-goal {v("combat-misses")} c:+ 1)', setv('sample', 8)]))
        # Destroying the visible objective must not cut the landed group's
        # strings. Probe a bounded ring around the sealed objective. Command
        # same-zone mission members that are not already actively attacking;
        # stale movement or under-attack state must not deadlock continuation.
        # A visible hostile found on any later sample
        # still takes priority over these exploratory movements.
        probes = [(32, 0), (-32, 0), (0, 32), (0, -32),
                  (64, 0), (-64, 0), (0, 64), (0, -64),
                  (96, 0), (-96, 0), (0, 96), (0, -96)]
        for miss, (dx, dy) in enumerate(probes, 1):
            actions = [f'(up-copy-point {v("clear-x")} {v("target-x")})']
            if dx:
                actions.append(f'(up-modify-goal {v("clear-x")} c:{"+" if dx > 0 else "-"} {abs(dx)})')
            if dy:
                actions.append(f'(up-modify-goal {v("clear-y")} c:{"+" if dy > 0 else "-"} {abs(dy)})')
            actions += [f'(up-bound-point {v("x")} {v("clear-x")})',
                        f'(up-copy-point {v("clear-x")} {v("x")})',
                        setv('zone', -1), f'(up-get-point-zone {v("clear-x")} {v("zone")})',
                        setv('sample', 9)]
            out.append(rule([f'(goal {v("state")} 6)', f'(goal {v("sample")} 8)',
                             f'(goal {v("combat-misses")} {miss})'], actions))
        out.append(rule([f'(goal {v("state")} 6)', f'(goal {v("sample")} 9)',
                         f'(up-compare-goal {v("zone")} g:== {v("target-zone")})'], [
            *members(), '(up-remove-objects search-local object-data-garrisoned == 1)',
            f'(up-remove-objects search-local object-data-map-zone-id g:!= {v("target-zone")})',
            '(up-remove-objects search-local object-data-action == actionid-attack)',
            f'(up-target-point {v("clear-x")} action-move -1 stance-aggressive)', setv('sample', 6)]))
        out.append(rule([f'(goal {v("state")} 6)', f'(goal {v("sample")} 9)',
                         f'(up-compare-goal {v("zone")} g:!= {v("target-zone")})'],
                        [setv('sample', 6)]))
        out.append(rule([f'(goal {v("state")} 6)',
                         f'(up-compare-goal {v("combat-misses")} c:>= 13)'],
                        [setv('state', 5), setv('reason', 12), *log(12)]))
        out.append(rule([f'(goal {v("state")} 5)'], [
            '(up-full-reset-search)', f'(up-set-group search-local c: {g})',
            '(up-remove-objects search-local object-data-player != my-player-number)',
            f'(up-remove-objects search-local object-data-group-flag != {g})',
            f'(up-create-group 0 0 c: {g})', f'(up-modify-group-flag 0 c: {g})',
            f'(up-reset-group c: {g})', setv('state', 0), setv('hull', -1), setv('sample', 0)]))
    # Invalid or unallocated admission never falls into the removed singleton
    # voyage path. Preserve cargo with its existing preparation recovery owner.
    out.append(rule(['(goal gl-transport-route-state TRANSPORT-ROUTE-DEPARTURE-START)'], [
        '(set-goal gl-transport-route-state TRANSPORT-ROUTE-SCREEN-RECALL)']))
    out.append(rule(['(true)'], ['(up-modify-sn sn-focus-player-number g:= gl-assault-mission-focus)']))
    return '\n\n'.join(out) + '\n'


def fallback_enemy_scan():
    out = [';Generated bounded literal-player hostility gate. No engine enemy iterator.',
           ';The caller retains the original all-enemy waypoint AND landing danger scan.']
    scan = '(goal gl-transport-route-state TRANSPORT-ROUTE-UNSCREENED-SCAN)'
    out.append(rule([scan], ['(set-goal gl-assault-fallback-hostile NO)']))
    for p in range(1, 9):
        out.append(rule([scan, f'(goal gl-assault-fallback-player {p})',
                         f'(player-in-game {p})', f'(stance-toward {p} enemy)'],
                        ['(set-goal gl-assault-fallback-hostile YES)']))
    return '\n\n'.join(out) + '\n'


def preparation_ownership():
    """Guard acknowledged preparation leases, never the three dispatched slots.

    Only an idle, unowned original hull may be reclaimed for terminal recovery.
    A foreign/moving/attacked hull is left alone; the failed preparation releases
    only its own passenger flags. No STOP or retry loop is introduced.
    """
    out = [';Generated by tools/generate_assault_missions.py. T17 preparation lease guard.',
           ';Claim acknowledgement is in rawai-military.per. This catches later loss.',
           ';No active independent voyage is eligible for this handler.']
    kinds = (
        ('migration', 'gl-island-migration-state', 'gl-island-migration-transport-id',
         'migration-transport-group', 'migration-boarding-group', 'MIGRATION-',
         ['BOARDING', 'LOADING', 'CHECK-LOAD', 'ISSUE-BOARD', 'OWNERSHIP-CLAIM',
          'LOAD-DIAG-FIND', 'LOAD-DIAG-PASSENGER', 'LOAD-DIAG-APPLY',
          'ROUTE-PREPARE', 'ROUTE-LEFT', 'ROUTE-RIGHT', 'ROUTE-APPLY'],
         'gl-island-migration-origin-x', 'gl-island-migration-focus', 't-island-migration'),
        ('assault', 'gl-transport-route-state', 'gl-transport-route-id',
         'attack-transport-group', 'attack-boarding-group', 'TRANSPORT-ROUTE-',
         ['LOAD-SELECT', 'LOAD-ISSUE', 'LOAD-WAIT', 'LOAD-CHECK', 'LOAD-READY',
           'LOAD-DIAG-FIND', 'LOAD-DIAG-PASSENGER', 'LOAD-DIAG-APPLY', 'LOAD-PARTIAL-MANIFEST'],
         'gl-transport-route-origin-x', 'gl-transport-route-focus', 't-transport-route'))
    for kind, state, hull, group, passengers, prefix, phases, origin, focus, timer in kinds:
        facts = [f'(goal {state} {prefix}{phase})' for phase in phases]
        active = facts[-1]
        # Keep the identical binary OR tree, but never serialize the entire
        # expression onto a 600+ byte physical line (T17 startup ERR2005).
        for fact in reversed(facts[:-1]):
            active = f'(or {fact}\n\t\t' + active.replace('\n', '\n\t') + ')'
        lost = [f'(goal {state} {prefix}OWNER-LOST)']
        select = ['(up-full-reset-search)', f'(up-add-object-by-id search-local g: {hull})']
        owner = ['(up-set-target-object search-local c: 0)',
                 '(up-object-data object-data-player == my-player-number)',
                 f'(up-object-data object-data-group-flag == {group})']
        out.append(rule([active], ['(set-goal gl-transport-preparation-owned NO)', *select]))
        out.append(rule([active, *owner], ['(set-goal gl-transport-preparation-owned YES)']))
        out.append(rule([active, '(goal gl-transport-preparation-owned NO)'],
                        [f'(set-goal {state} {prefix}OWNER-LOST)']))
        out.append(rule(lost, [*select,
            f'(up-chat-data-to-all "RAW17 {kind} owner lost hull: %d" g: {hull})']))
        out.append(rule([*lost, '(up-set-target-object search-local c: 0)'], [
            '(up-get-object-data object-data-group-flag gl-transport-observed-value)',
            '(up-chat-data-to-all "RAW17 actual owner flag: %d" g: gl-transport-observed-value)',
            '(up-get-object-data object-data-order gl-transport-observed-value)',
            '(up-chat-data-to-all "RAW17 actual hull order: %d" g: gl-transport-observed-value)']))
        recover = [*lost, '(up-set-target-object search-local c: 0)',
                   '(up-object-data object-data-player == my-player-number)',
                   '(up-object-data object-data-group-flag < 0)',
                   '(up-object-data object-data-idling == 1)',
                   '(up-object-data object-data-under-attack == 0)']
        if kind == 'assault': recover += ['(goal gl-transport-route-script-load YES)']
        out.append(rule(recover, [
            '(up-remove-objects search-local object-data-player != my-player-number)',
            '(up-remove-objects search-local object-data-group-flag >= 0)',
            '(up-remove-objects search-local object-data-idling != 1)',
            '(up-remove-objects search-local object-data-under-attack > 0)',
            f'(up-create-group 0 0 c: {group})', f'(up-modify-group-flag 1 c: {group})']))
        recovery = [
            ';OWNERSHIP command: ' + group + '.',
            '(up-remove-objects search-local object-data-player != my-player-number)',
            f'(up-remove-objects search-local object-data-group-flag != {group})',
            f'(up-target-point {origin} action-unload -1 stance-no-attack)',
            f'(up-chat-data-to-all "RAW17 {kind} owner recovery hull: %d" g: {hull})',
            f'(up-modify-sn sn-focus-player-number g:= {focus})',
            f'(up-set-timer c: {timer} c: 15)']
        if kind == 'migration':
            recovery += ['(set-goal gl-island-migration-route-waits 0)',
                         '(set-goal gl-island-migration-rejection-armed NO)',
                         f'(set-goal {state} MIGRATION-RETURNING)']
        else:
            recovery += ['(set-goal gl-route-unload-attempts 0)',
                         f'(set-goal {state} TRANSPORT-ROUTE-RECOVERY-WAIT)']
        out.append(rule([*lost, *owner], recovery))
        out.append(rule(lost, [
            f'(up-chat-data-to-all "RAW17 {kind} owner yield hull: %d" g: {hull})',
            '(up-full-reset-search)', f'(up-set-group search-local c: {passengers})',
            '(up-remove-objects search-local object-data-player != my-player-number)',
            f'(up-remove-objects search-local object-data-group-flag != {passengers})',
            f'(up-create-group 0 0 c: {passengers})',
            f'(up-modify-group-flag 0 c: {passengers})', f'(up-reset-group c: {passengers})',
            f'(up-modify-sn sn-focus-player-number g:= {focus})',
            f'(up-set-timer c: {timer} c: 60)', f'(set-goal {state} {prefix}IDLE)']))
    return '\n\n'.join(out) + '\n'


def outputs():
    return {**plan_outputs(), 'rawai-assault-mission-defs.per': definitions(),
            'rawai-assault-admission.per': admission(), 'rawai-assault-missions.per': missions(),
            'rawai-transport-preparation-ownership.per': preparation_ownership(),
            'rawai-assault-enemy-scan.per': fallback_enemy_scan(),
            'rawai-assault-cancel-details.per': ';Generated diagnostic-only terminal report; code 4 namespace, not RAW3 event 4.\n' +
                cancellation_details(['(goal gl-transport-route-state TRANSPORT-ROUTE-UNSCREENED-DENY)',
                                      '(goal gl-assault-fallback-denial 4)'], 2) + '\n'}


def patch():
    print('*** Begin Patch')
    for name, text in outputs().items():
        path = ROOT / name
        if not path.exists():
            print('*** Add File: ' + path.as_posix())
            print('\n'.join('+' + line for line in text.splitlines()))
        else:
            old = path.read_text(encoding='utf-8-sig')
            if old == text: continue
            print('*** Update File: ' + path.as_posix())
            for line in list(difflib.unified_diff(old.splitlines(), text.splitlines(), n=3))[2:]:
                print('@@' if line.startswith('@@') else line)
    print('*** End Patch')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    if args.check:
        mismatches = [name for name, text in outputs().items()
                      if not (ROOT / name).exists() or (ROOT / name).read_text(encoding='utf-8-sig') != text]
        print('assault generation ' + ('FAIL: ' + ', '.join(mismatches) if mismatches else 'PASS'))
        raise SystemExit(bool(mismatches))
    patch()
