"""Bounded coastal construction, using real mobile objects for path queries.

Geometry reuses the shoreline resolver's finite candidates / exact-water
validation concept. No terrain IDs, building path queries or global retasking.
AIRef cache 2026-08-30: up-path-distance option 1 requires an open exact tile;
option 0 allows vicinity. up-build-line is an issuance, NOT foundation proof.
"""
from pathlib import Path
import argparse
from generate_assault_missions import rule

ROOT = Path(__file__).resolve().parents[1]
FIELDS = ('clock', 'next', 'deficit-since', 'minimum', 'reason', 'reported',
          'diag-next', 'anchor', 'sector', 'direction', 'stage', 'count', 'ship',
          'water-zone', 'zone', 'worker', 'until', 'foundation', 'memory-index',
          'anchor-x', 'anchor-y', 'w1-x', 'w1-y', 'w2-x', 'w2-y', 'w3-x', 'w3-y',
          'w4-x', 'w4-y', 'bounded-x', 'bounded-y', 'sample')
OFFSETS = tuple((dx*r, dy*r) for r in (12, 24, 40)
                for dx, dy in ((1,0), (0,1), (-1,0), (0,-1), (1,1), (-1,1), (-1,-1), (1,-1)))
DIRECTIONS = ((1,0), (0,1), (-1,0), (0,-1))


def definitions():
    names = list(FIELDS) + [f'memory{i}-{f}' for i in range(4) for f in ('x','y','until')]
    return ';Generated coastal construction storage, no timer/group allocation.\n' + '\n'.join(
        f'(defconst gl-sy-{name} {15600+i})' for i, name in enumerate(names)) + '\n'


def generate():
    out = [';Generated by tools/generate_shipyard_placement.py. Reasons: 0 satisfied,',
           ';1 unaffordable/unavailable, 2 pending, 3 missing/lost foundation,',
           ';4 worker hold/unreachable, 5 tech saving, 6 coast/exit rejected, 7 constructing.',
           ';Native builder assignment remains authoritative; reaching a point is not completion.']
    def add(f, a): out.append(rule(f, a))
    def stage(n): return [f'(goal gl-sy-stage {n})']
    def reset(reason): return [f'(set-goal gl-sy-reason {reason})', '(set-goal gl-sy-stage 90)']
    def deadline(seconds): return ['(up-modify-goal gl-sy-until g:= gl-sy-clock)', f'(up-modify-goal gl-sy-until c:+ {seconds})']
    def point(name, dx, dy):
        a = [f'(up-copy-point gl-sy-{name}-x gl-shipyard-x)']
        for axis, v in (('x',dx), ('y',dy)):
            if v: a.append(f'(up-modify-goal gl-sy-{name}-{axis} c:{"+" if v>0 else "-"} {abs(v)})')
        return a
    water = '(or (goal map-type LAKE) (or (goal map-type RIVERS) (or (goal map-type ISLANDS) (goal map-type TEAM-ISLANDS))))'
    add(['(true)'], ['(set-goal gl-sy-stage 0)', '(set-goal gl-sy-next 0)',
        '(set-goal gl-sy-anchor -1)', '(set-goal gl-sy-sector 0)', '(set-goal gl-sy-deficit-since 0)',
        '(set-goal gl-sy-memory-index 0)', '(set-goal gl-sy-diag-next 0)',
        '(set-goal gl-sy-reported -1)', *[f'(set-goal gl-sy-memory{i}-until 0)' for i in range(4)], '(disable-self)'])
    add(['(true)'], ['(up-get-fact game-time 0 gl-sy-clock)',
        '(up-modify-goal gl-sy-minimum g:= desired-number-shipyards)', '(up-modify-goal gl-sy-minimum c:min 2)',
        '(up-modify-goal gl-sy-minimum c:max 1)', '(set-goal gl-sy-sample 0)'])
    for m, cap in (('LAKE',4), ('RIVERS',6)):
        add([f'(goal map-type {m})', f'(up-compare-goal desired-number-shipyards c:> {cap})'],
            [f'(up-modify-goal desired-number-shipyards c:= {cap})'])
    add(['(building-type-count shipyard g:>= gl-sy-minimum)'], ['(set-goal gl-sy-deficit-since 0)'])
    add([water, '(current-age >= early-antiquity-age)', '(building-type-count port > 0)',
         '(building-type-count shipyard g:< gl-sy-minimum)', '(goal gl-sy-deficit-since 0)'],
        ['(up-modify-goal gl-sy-deficit-since g:= gl-sy-clock)', '(up-modify-goal gl-sy-deficit-since c:+ 90)'])
    add([*stage(0), '(up-compare-goal gl-sy-clock g:>= gl-sy-next)'],
        ['(set-goal gl-sy-sample 1)', '(set-goal gl-sy-reason 0)',
         '(up-modify-goal gl-sy-next g:= gl-sy-clock)', '(up-modify-goal gl-sy-next c:+ 2)'])
    common = [*stage(0), '(goal gl-sy-sample 1)', water, '(current-age >= early-antiquity-age)',
              '(building-type-count port > 0)', '(goal shipyard-placement-state SHIPYARD-IDLE)']
    # Preserve the high-priority first-yard opening, including its wood reserve.
    add([*common, '(building-type-count-total shipyard == 0)', '(wood-amount > 250)',
         '(up-pending-objects c: shipyard <= 0)', '(not (up-pending-placement c: shipyard))',
         '(can-build shipyard)'], ['(set-goal shipyard-placement-state SHIPYARD-ANCHOR)'])
    add([*common, '(goal wait-techup-requirements NO)', '(can-afford-building shipyard)',
         '(building-type-count-total shipyard g:< desired-number-shipyards)',
         '(up-pending-objects c: shipyard <= 0)', '(not (up-pending-placement c: shipyard))',
         '(can-build shipyard)'], ['(set-goal shipyard-placement-state SHIPYARD-ANCHOR)'])
    # Only a persistent deficit BELOW min(desired,2) bypasses the policy hold.
    # No escrow release: available resources must still pay the actual cost.
    add([*common, '(goal wait-techup-requirements YES)', '(building-type-count-total shipyard >= 1)',
         '(building-type-count-total shipyard g:< gl-sy-minimum)', '(goal gl-owner-worker-hold NO)',
         '(up-compare-goal gl-sy-deficit-since c:> 0)', '(up-compare-goal gl-sy-clock g:>= gl-sy-deficit-since)',
         '(can-afford-building shipyard)', '(can-build shipyard)',
         '(up-pending-objects c: shipyard <= 0)', '(not (up-pending-placement c: shipyard))'],
        ['(set-goal shipyard-placement-state SHIPYARD-ANCHOR)'])
    for facts, reason in ((['(goal wait-techup-requirements YES)'],5),
            (['(not (can-build shipyard))'],1), (['(goal gl-owner-worker-hold YES)'],4),
            (['(or (up-pending-objects c: shipyard >= 1) (up-pending-placement c: shipyard))'],2)):
        add([*common, '(building-type-count shipyard g:< gl-sy-minimum)', *facts], [f'(set-goal gl-sy-reason {reason})'])
    add([*stage(0), '(goal shipyard-placement-state SHIPYARD-ANCHOR)'], [
        '(up-full-reset-search)', '(up-filter-status c: status-ready c: list-active)',
        '(up-find-local c: port c: 40)', '(up-find-local c: shipyard c: 40)',
        '(up-remove-objects search-local object-data-id g:<= gl-sy-anchor)',
        '(up-clean-search search-local object-data-id search-order-asc)', '(set-goal gl-sy-stage 1)'])
    add([*stage(1), '(up-set-target-object search-local c: 0)'], [
        '(up-get-object-data object-data-id gl-sy-anchor)', '(up-get-point position-object gl-sy-anchor-x)',
        '(set-goal gl-sy-stage 2)'])
    add(stage(1), ['(set-goal gl-sy-anchor -1)', *reset(6)])
    # Exactly one candidate per sweep; rotate sectors AND anchors on rejection.
    for index,(dx,dy) in enumerate(OFFSETS):
        add([*stage(2), f'(goal gl-sy-sector {index})'], [
            '(up-copy-point gl-shipyard-x gl-sy-anchor-x)',
            f'(up-modify-goal gl-shipyard-x c:+ {dx})', f'(up-modify-goal gl-shipyard-y c:+ {dy})',
            '(up-bound-point gl-sy-bounded-x gl-shipyard-x)',
            '(set-goal gl-sy-direction 0)', '(set-goal gl-sy-stage 3)'])
    add([*stage(3), '(or (up-compare-goal gl-shipyard-x g:!= gl-sy-bounded-x) (up-compare-goal gl-shipyard-y g:!= gl-sy-bounded-y))'], reset(6))
    for i in range(4):
        add([*stage(3), f'(up-compare-goal gl-sy-clock g:< gl-sy-memory{i}-until)'], [
            '(up-set-target-point gl-shipyard-x)', f'(up-get-point-distance gl-sy-memory{i}-x 0 gl-sy-count)'])
        add([*stage(3), f'(up-compare-goal gl-sy-clock g:< gl-sy-memory{i}-until)', '(up-compare-goal gl-sy-count c:< 10)'], reset(6))
    add([*stage(3), '(not (up-can-build-line 0 gl-shipyard-x c: shipyard))'], reset(6))
    add(stage(3), ['(up-full-reset-search)', '(up-set-target-point gl-shipyard-x)',
        '(up-filter-distance c: -1 c: 10)', '(up-find-local c: port c: 40)', '(up-find-local c: shipyard c: 40)',
        '(up-filter-status c: status-pending c: list-active)', '(up-find-status-local c: shipyard c: 40)',
        '(up-get-search-state local-total)', '(set-goal gl-sy-stage 4)'])
    add([*stage(4), '(up-compare-goal local-total c:> 0)'], reset(6))
    add(stage(4), ['(up-full-reset-search)', '(up-set-target-point gl-shipyard-x)',
        '(up-filter-distance c: -1 c: 64)', '(up-find-local c: warship-class c: 40)',
        '(up-find-local c: transport-ship c: 40)', '(up-find-local c: fishing-ship-class c: 40)',
        '(up-clean-search search-local object-data-distance search-order-asc)', '(set-goal gl-sy-stage 5)'])
    add([*stage(5), '(up-set-target-object search-local c: 0)'], [
        '(up-get-object-data object-data-id gl-sy-ship)',
        '(up-get-object-data object-data-map-zone-id gl-sy-water-zone)', '(set-goal gl-sy-stage 6)'])
    add(stage(5), reset(6))
    # Test four orientations, never manufacture water by clipping a land tile.
    for i,(dx,dy) in enumerate(DIRECTIONS):
        add([*stage(6), f'(goal gl-sy-direction {i})'], [
            *point('w1',dx*6,dy*6), *point('w2',dx*12,dy*12),
            *point('w3',dx*12-dy*4,dy*12+dx*4), *point('w4',dx*12+dy*4,dy*12-dx*4),
            '(set-goal gl-sy-stage 7)'])
    for point_name in ('w1','w2','w3','w4'):
        x=f'gl-sy-{point_name}-x'
        add(stage(7), [f'(up-bound-point gl-sy-bounded-x {x})', f'(up-get-point-zone {x} gl-sy-zone)',
            '(up-full-reset-search)', '(up-add-object-by-id search-local g: gl-sy-ship)'])
        add([*stage(7), f'(or (up-compare-goal {x} g:!= gl-sy-bounded-x) (up-compare-goal {x[:-1]}y g:!= gl-sy-bounded-y))'], ['(set-goal gl-sy-stage 8)'])
        add([*stage(7), '(up-compare-goal gl-sy-zone g:!= gl-sy-water-zone)'], ['(set-goal gl-sy-stage 8)'])
        add([*stage(7), '(not (up-set-target-object search-local c: 0))'], ['(set-goal gl-sy-stage 8)'])
        add([*stage(7), '(up-set-target-object search-local c: 0)', '(up-object-data object-data-player != my-player-number)'], ['(set-goal gl-sy-stage 8)'])
        add([*stage(7), '(up-set-target-object search-local c: 0)', f'(up-path-distance {x} 1 == 65535)'], ['(set-goal gl-sy-stage 8)'])
    add(stage(8), ['(up-modify-goal gl-sy-direction c:+ 1)', '(set-goal gl-sy-stage 6)'])
    add([*stage(6), '(up-compare-goal gl-sy-direction c:>= 4)'], reset(6))
    add(stage(7), ['(up-full-reset-search)', '(up-set-target-point gl-shipyard-x)',
        '(up-filter-distance c: -1 c: 40)', '(up-find-local c: villager-class c: 40)',
        '(up-remove-objects search-local object-data-player != my-player-number)',
        '(up-remove-objects search-local object-data-group-flag >= 0)',
        '(up-remove-objects search-local object-data-garrisoned == 1)',
        '(up-remove-objects search-local object-data-under-attack > 0)',
        '(up-remove-objects search-local object-data-action == actionid-build)',
        '(up-remove-objects search-local object-data-action == actionid-repair)',
        '(up-remove-objects search-local object-data-id g:== gl-boar-lurer-id)',
        '(up-clean-search search-local object-data-distance search-order-asc)', '(set-goal gl-sy-stage 9)'])
    add([*stage(9), '(up-set-target-object search-local c: 0)', '(up-path-distance gl-shipyard-x 0 < 64)'], [
        '(up-get-object-data object-data-id gl-sy-worker)', '(set-goal gl-sy-stage 10)'])
    add(stage(9), reset(4))
    add([*stage(10), '(goal gl-owner-worker-hold NO)', '(can-build shipyard)', '(can-afford-building shipyard)',
         '(or (goal wait-techup-requirements NO) (or (building-type-count-total shipyard == 0)\n\t(and (building-type-count-total shipyard g:< gl-sy-minimum) (up-compare-goal gl-sy-clock g:>= gl-sy-deficit-since))))',
         '(or (building-type-count-total shipyard == 0) (building-type-count-total shipyard g:< desired-number-shipyards))',
         '(up-pending-objects c: shipyard <= 0)', '(not (up-pending-placement c: shipyard))',
         '(up-can-build-line 0 gl-shipyard-x c: shipyard)'], [
        '(up-build-line gl-shipyard-x gl-shipyard-x c: shipyard)', *deadline(24),
        '(set-goal gl-sy-foundation -1)', '(set-goal gl-sy-stage 20)'])
    add(stage(10), reset(4))
    # Pending count anywhere is not proof: verify the actual own object at issue.
    add(stage(20), ['(up-full-reset-search)', '(up-set-target-point gl-shipyard-x)',
        '(up-filter-distance c: -1 c: 2)', '(up-filter-status c: status-pending c: list-active)',
        '(up-find-status-local c: shipyard c: 40)', '(up-filter-status c: status-ready c: list-active)',
        '(up-find-status-local c: shipyard c: 40)', '(set-goal gl-sy-stage 21)'])
    add([*stage(21), '(up-set-target-object search-local c: 0)', '(up-object-data object-data-player == my-player-number)'], [
        '(up-get-object-data object-data-id gl-sy-foundation)', '(set-goal gl-sy-reason 7)', *deadline(180), '(set-goal gl-sy-stage 22)'])
    add([*stage(21), '(up-compare-goal gl-sy-clock g:>= gl-sy-until)'], reset(3))
    add(stage(21), ['(set-goal gl-sy-stage 20)'])
    add(stage(22), ['(up-full-reset-search)', '(up-add-object-by-id search-local g: gl-sy-foundation)'])
    add([*stage(22), '(up-set-target-object search-local c: 0)', '(up-object-data object-data-player == my-player-number)',
         '(up-object-data object-data-status == status-ready)'], ['(set-goal gl-sy-reason 0)', '(set-goal gl-sy-stage 91)'])
    add([*stage(22), '(not (up-set-target-object search-local c: 0))'], reset(3))
    add([*stage(22), '(up-compare-goal gl-sy-clock g:>= gl-sy-until)'], reset(4))
    for i in range(4):
        add([*stage(90), f'(goal gl-sy-memory-index {i})'], [
            f'(up-copy-point gl-sy-memory{i}-x gl-shipyard-x)', f'(up-modify-goal gl-sy-memory{i}-until g:= gl-sy-clock)',
            f'(up-modify-goal gl-sy-memory{i}-until c:+ 180)', '(set-goal gl-sy-stage 91)'])
    add(stage(91), ['(up-modify-goal gl-sy-memory-index c:+ 1)', '(up-modify-goal gl-sy-memory-index c:mod 4)',
        '(up-modify-goal gl-sy-sector c:+ 1)', f'(up-modify-goal gl-sy-sector c:mod {len(OFFSETS)})',
        '(set-goal shipyard-placement-state SHIPYARD-IDLE)', '(set-goal gl-sy-stage 0)'])
    add(['(up-compare-goal gl-sy-clock g:>= gl-sy-diag-next)', '(up-compare-goal gl-sy-reason g:!= gl-sy-reported)'], [
        '(up-chat-data-to-all str-t12-diag-id c: 410)', '(up-chat-data-to-all str-t12-diag-value g: gl-sy-reason)',
        '(up-modify-goal gl-sy-reported g:= gl-sy-reason)', '(up-modify-goal gl-sy-diag-next g:= gl-sy-clock)',
        '(up-modify-goal gl-sy-diag-next c:+ 60)'])
    return '\n\n'.join(out)+'\n'


def outputs():
    return {'rawai-shipyard-defs.per': definitions(), 'rawai-specialplacement.per': generate()}


if __name__ == '__main__':
    parser=argparse.ArgumentParser(); parser.add_argument('--write',action='store_true'); args=parser.parse_args()
    for name, text in outputs().items():
        path=ROOT/name
        if args.write: path.write_text(text, encoding='utf-8')
        elif not path.exists() or path.read_text(encoding='utf-8-sig') != text: raise SystemExit(f'stale: {name}')
