"""Generate the bounded, preparation-only migration shoreline resolver."""
from shoreline_resolver import (COARSE_LIMIT, COARSE_STEP, MEMORY_RADIUS,
                                REFINE_LIMIT, REFINE_STEP, SHORE_OFFSETS)


def rule(facts, actions):
    return '(defrule\n\t' + '\n\t'.join(facts) + '\n=>\n\t' + '\n\t'.join(actions) + '\n)'


def migration_shoreline():
    out = [
        ';Generated by tools/generate_migration_shoreline.py.',
        f';Mechanical bound: {COARSE_LIMIT} coarse samples, four refinements, five coast sectors,',
        ';and exactly two exact-hull path queries per path-tested sector.',
    ]

    def emit(facts, actions):
        out.append(rule(facts, actions))

    def state(name):
        return f'(goal gl-island-migration-state {name})'

    def go(name):
        return f'(set-goal gl-island-migration-state {name})'

    def cp(dst, src):
        return f'(up-modify-goal {dst} g:= {src})'

    def select_hull():
        return [
            '(set-strategic-number sn-focus-player-number my-player-number)',
            '(up-full-reset-search)',
            '(up-add-object-by-id search-local g: gl-island-migration-transport-id)',
            '(up-remove-objects search-local object-data-player != my-player-number)',
            '(up-remove-objects search-local object-data-group-flag != migration-transport-group)',
        ]

    emit(['(true)'], [
        '(set-goal gl-msr-write 1)',
        *[f'(set-goal gl-msr-memory{i}-until 0)' for i in range(1, 5)],
        '(disable-self)',
    ])
    emit([state('MIGRATION-SHORE-INIT')], [*select_hull(), go('MIGRATION-SHORE-HULL')])
    emit([state('MIGRATION-SHORE-HULL'), '(up-set-target-object search-local c: 0)'], [
        '(up-get-point position-object gl-msr-hull-x)',
        '(up-bound-point gl-msr-scan-x gl-island-migration-target-x)',
        '(up-bound-point gl-msr-land-x gl-island-migration-target-x)',
        '(set-goal gl-msr-steps 0)', '(set-goal gl-msr-refines 0)',
        go('MIGRATION-SHORE-COARSE'),
    ])
    emit([state('MIGRATION-SHORE-HULL'), '(not (up-set-target-object search-local c: 0))'], [
        '(up-modify-sn sn-focus-player-number g:= gl-island-migration-focus)',
        '(up-set-timer c: t-island-migration c: 60)', go('MIGRATION-IDLE'),
    ])
    emit([state('MIGRATION-SHORE-COARSE'),
          f'(up-compare-goal gl-msr-steps c:>= {COARSE_LIMIT})'],
         [go('MIGRATION-SHORE-EXHAUSTED')])
    emit([state('MIGRATION-SHORE-COARSE'),
          f'(up-compare-goal gl-msr-steps c:< {COARSE_LIMIT})'], [
        f'(up-lerp-tiles gl-msr-scan-x gl-msr-hull-x c: {COARSE_STEP})',
        '(up-bound-point gl-msr-scan-x gl-msr-scan-x)',
        '(set-goal gl-msr-zone -2)', '(up-get-point-zone gl-msr-scan-x gl-msr-zone)',
        '(up-modify-goal gl-msr-steps c:+ 1)', go('MIGRATION-SHORE-COARSE-CHECK'),
    ])
    emit([state('MIGRATION-SHORE-COARSE-CHECK'),
          '(up-compare-goal gl-msr-zone g:== gl-island-migration-zone)'], [
        '(up-bound-point gl-msr-land-x gl-msr-scan-x)', go('MIGRATION-SHORE-COARSE'),
    ])
    emit([state('MIGRATION-SHORE-COARSE-CHECK'),
          '(up-compare-goal gl-msr-zone g:!= gl-island-migration-zone)'], [
        '(up-bound-point gl-msr-water-x gl-msr-scan-x)',
        '(up-bound-point gl-msr-refine-x gl-msr-land-x)',
        '(set-goal gl-msr-refines 0)', go('MIGRATION-SHORE-REFINE'),
    ])
    emit([state('MIGRATION-SHORE-REFINE'),
          f'(up-compare-goal gl-msr-refines c:>= {REFINE_LIMIT})'], [
        '(set-goal gl-msr-candidate 0)', go('MIGRATION-SHORE-CANDIDATE'),
    ])
    emit([state('MIGRATION-SHORE-REFINE'),
          f'(up-compare-goal gl-msr-refines c:< {REFINE_LIMIT})'], [
        f'(up-lerp-tiles gl-msr-refine-x gl-msr-water-x c: {REFINE_STEP})',
        '(up-bound-point gl-msr-refine-x gl-msr-refine-x)',
        '(set-goal gl-msr-zone -2)', '(up-get-point-zone gl-msr-refine-x gl-msr-zone)',
        '(up-modify-goal gl-msr-refines c:+ 1)', go('MIGRATION-SHORE-REFINE-CHECK'),
    ])
    emit([state('MIGRATION-SHORE-REFINE-CHECK'),
          '(up-compare-goal gl-msr-zone g:== gl-island-migration-zone)'], [
        '(up-bound-point gl-msr-land-x gl-msr-refine-x)', go('MIGRATION-SHORE-REFINE'),
    ])
    emit([state('MIGRATION-SHORE-REFINE-CHECK'),
          '(up-compare-goal gl-msr-zone g:!= gl-island-migration-zone)'], [
        '(up-bound-point gl-msr-water-x gl-msr-refine-x)',
        '(set-goal gl-msr-candidate 0)', go('MIGRATION-SHORE-CANDIDATE'),
    ])
    emit([state('MIGRATION-SHORE-CANDIDATE'),
          f'(up-compare-goal gl-msr-candidate c:>= {len(SHORE_OFFSETS)})'],
         [go('MIGRATION-SHORE-EXHAUSTED')])
    for index, offset in enumerate(SHORE_OFFSETS):
        actions = [
            '(up-bound-point gl-island-migration-route-waypoint-x gl-msr-land-x)',
            '(up-bound-point gl-msr-candidate-water-x gl-msr-water-x)',
        ]
        if offset:
            actions += [
                f'(up-cross-tiles gl-island-migration-route-waypoint-x gl-msr-water-x c: {offset})',
                f'(up-cross-tiles gl-msr-candidate-water-x gl-msr-land-x c: {-offset})',
            ]
        actions += [
            '(up-bound-point gl-island-migration-route-waypoint-x gl-island-migration-route-waypoint-x)',
            '(up-bound-point gl-msr-candidate-water-x gl-msr-candidate-water-x)',
            '(set-goal gl-msr-zone -2)',
            '(up-get-point-zone gl-island-migration-route-waypoint-x gl-msr-zone)',
            '(set-goal gl-msr-water-zone -2)',
            '(up-get-point-zone gl-msr-candidate-water-x gl-msr-water-zone)',
            '(set-goal gl-msr-blocked NO)',
            cp('gl-msr-min-x', 'gl-island-migration-route-waypoint-x'),
            f'(up-modify-goal gl-msr-min-x c:- {MEMORY_RADIUS})',
            cp('gl-msr-max-x', 'gl-island-migration-route-waypoint-x'),
            f'(up-modify-goal gl-msr-max-x c:+ {MEMORY_RADIUS})',
            cp('gl-msr-min-y', 'gl-island-migration-route-waypoint-y'),
            f'(up-modify-goal gl-msr-min-y c:- {MEMORY_RADIUS})',
            cp('gl-msr-max-y', 'gl-island-migration-route-waypoint-y'),
            f'(up-modify-goal gl-msr-max-y c:+ {MEMORY_RADIUS})',
            go('MIGRATION-SHORE-CACHE'),
        ]
        emit([state('MIGRATION-SHORE-CANDIDATE'), f'(goal gl-msr-candidate {index})'], actions)
    for index in range(1, 5):
        emit([state('MIGRATION-SHORE-CACHE'),
              f'(up-compare-goal gl-game-time g:< gl-msr-memory{index}-until)',
              f'(up-compare-goal gl-msr-memory{index}-x g:>= gl-msr-min-x)',
              f'(up-compare-goal gl-msr-memory{index}-x g:<= gl-msr-max-x)',
              f'(up-compare-goal gl-msr-memory{index}-y g:>= gl-msr-min-y)',
              f'(up-compare-goal gl-msr-memory{index}-y g:<= gl-msr-max-y)'],
             ['(set-goal gl-msr-blocked YES)'])
    advance = ['(up-modify-goal gl-msr-candidate c:+ 1)', go('MIGRATION-SHORE-CANDIDATE')]
    emit([state('MIGRATION-SHORE-CACHE'), '(goal gl-msr-blocked YES)'], advance)
    emit([state('MIGRATION-SHORE-CACHE'),
          '(or (up-compare-goal gl-msr-zone g:!= gl-island-migration-zone)\n'
          '\t(or (up-compare-goal gl-msr-water-zone c:< 0)\n'
          '\t(up-compare-goal gl-msr-water-zone g:== gl-island-migration-zone)))'], advance)
    emit([state('MIGRATION-SHORE-CACHE')], [*select_hull(), go('MIGRATION-SHORE-PATH')])
    emit([state('MIGRATION-SHORE-PATH'), '(up-set-target-object search-local c: 0)'], [
        '(up-get-path-distance gl-msr-candidate-water-x 1 gl-msr-water-distance)',
        '(up-get-path-distance gl-island-migration-route-waypoint-x 0 gl-msr-land-distance)',
        go('MIGRATION-SHORE-PATH-RESULT'),
    ])
    emit([state('MIGRATION-SHORE-PATH'), '(not (up-set-target-object search-local c: 0))'],
         [go('MIGRATION-SHORE-EXHAUSTED')])
    emit([state('MIGRATION-SHORE-PATH-RESULT'),
          '(or (up-compare-goal gl-msr-water-distance c:< 0)\n'
          '\t(or (goal gl-msr-water-distance 65535)\n'
          '\t(or (up-compare-goal gl-msr-land-distance c:< 0)\n'
          '\t(goal gl-msr-land-distance 65535))))'],
         [go('MIGRATION-SHORE-REMEMBER')])
    emit([state('MIGRATION-SHORE-PATH-RESULT'),
          '(up-compare-goal gl-msr-water-distance c:>= 0)',
          '(up-compare-goal gl-msr-water-distance c:!= 65535)',
          '(up-compare-goal gl-msr-land-distance c:>= 0)',
          '(up-compare-goal gl-msr-land-distance c:!= 65535)'], [
        '(up-bound-point gl-msr-selected-water-x gl-msr-candidate-water-x)',
        '(up-bound-point gl-msr-selected-land-x gl-island-migration-route-waypoint-x)',
        '(up-modify-sn sn-focus-player-number g:= gl-island-migration-focus)',
        go('MIGRATION-ROUTE-PREPARE'),
    ])
    for index in range(1, 5):
        emit([state('MIGRATION-SHORE-REMEMBER'), f'(goal gl-msr-write {index})'], [
            cp(f'gl-msr-memory{index}-x', 'gl-island-migration-route-waypoint-x'),
            cp(f'gl-msr-memory{index}-y', 'gl-island-migration-route-waypoint-y'),
            cp(f'gl-msr-memory{index}-until', 'gl-game-time'),
            f'(up-modify-goal gl-msr-memory{index}-until c:+ 300)',
            f'(set-goal gl-msr-write {index % 4 + 1})', *advance,
        ])
    emit([state('MIGRATION-SHORE-EXHAUSTED')], [
        '(up-modify-goal gl-island-migration-rejected-zone3 g:= gl-island-migration-rejected-zone2)',
        '(up-modify-goal gl-island-migration-rejected-zone2 g:= gl-island-migration-rejected-zone)',
        '(up-modify-goal gl-island-migration-rejected-zone g:= gl-island-migration-zone)',
        '(set-goal gl-island-migration-rejection-armed NO)',
        '(set-goal gl-island-migration-route-waits 0)',
        *select_hull(),
        ';OWNERSHIP command: migration-transport-group.',
        '(up-target-point gl-home-anchor-x action-unload -1 stance-no-attack)',
        '(up-modify-sn sn-focus-player-number g:= gl-island-migration-focus)',
        '(up-set-timer c: t-island-migration c: 15)', go('MIGRATION-RETURNING'),
    ])
    return '\n\n'.join(out) + '\n'


def outputs():
    return {'rawai-migration-shoreline.per': migration_shoreline()}
