"""Generate repetitive per-player ownership policy as apply_patch input."""
from pathlib import Path
import difflib

ROOT = Path(__file__).resolve().parents[1]


def rule(facts, actions):
    return '(defrule\n\t' + '\n\t'.join(facts) + '\n=>\n\t' + '\n\t'.join(actions) + '\n)'


def emit(name, text):
    path = ROOT / name
    if not path.exists():
        print('*** Add File: ' + path.as_posix())
        print('\n'.join('+' + line for line in text.splitlines()))
        return
    old = path.read_text(encoding='utf-8-sig')
    if old == text:
        return
    print('*** Update File: ' + path.as_posix())
    # Repeated per-player rules have identical short contexts. Anchor the whole
    # generated file so apply_patch cannot place a hunk in the wrong player.
    for line in list(difflib.unified_diff(old.splitlines(), text.splitlines(), n=len(old.splitlines()) + 1))[2:]:
        print('@@' if line.startswith('@@') else line)


def safe_release(group):
    return ['(up-set-group search-local c: ' + group + ')',
            '(up-remove-objects search-local object-data-player != my-player-number)',
            '(up-remove-objects search-local object-data-group-flag != ' + group + ')',
            '(up-create-group 0 0 c: ' + group + ')',
            '(up-modify-group-flag 0 c: ' + group + ')',
            '(up-reset-group c: ' + group + ')']


def anchors():
    out = [';Generated by tools/generate_ownership_policy.py. First reliable TC only.']
    out.append(rule(['(true)'], [f'(set-goal gl-ally-home-{p}-{key} -1)'
                                for p in range(1, 9) for key in ('x', 'y', 'zone')]
                    + ['(disable-self)']))
    for p in range(1, 9):
        facts = [f'(goal gl-ally-home-{p}-x -1)', f'(player-in-game {p})']
        out.append(rule(facts, [
            '(up-modify-goal gl-owner-anchor-focus s:= sn-focus-player-number)',
            f'(set-strategic-number sn-focus-player-number {p})',
            '(up-full-reset-search)', '(up-filter-status c: status-ready c: list-active)',
            '(up-get-point position-focus point-x)', '(up-set-target-point point-x)',
            '(up-find-remote c: town-center c: 20)',
            f'(up-remove-objects search-remote object-data-player != {p})',
            '(up-clean-search search-remote object-data-distance search-order-asc)',
            '(up-modify-sn sn-focus-player-number g:= gl-owner-anchor-focus)']))
        out.append(rule(facts + ['(up-set-target-object search-remote c: 0)'], [
            f'(up-get-point position-object gl-ally-home-{p}-x)',
            f'(up-get-object-data object-data-map-zone-id gl-ally-home-{p}-zone)']))
    return '\n\n'.join(out) + '\n'


LAND = ('scout-cavalry-class', 'cavalry-archer-class', 'cavalry-class',
        'infantry-class', 'archery-class', 'siege-weapon-class')


def severe():
    out = [';Generated severe-home policy. No under-attack flag is used as proof.',
           ';Eight live hostile military within 24 tiles, in the home land zone.',
           ';Routine defense never reaches this ownership-preemption protocol.']
    out.append(rule(['(true)'], ['(set-goal gl-owner-severe-armed NO)']))
    for p in range(1, 9):
        facts = ['(up-timer-status t-defense-leash == timer-triggered)',
                 f'(stance-toward {p} enemy)', f'(player-in-game {p})',
                 '(up-compare-goal gl-home-zone c:>= 0)']
        out.append(rule(facts, [
            '(up-modify-goal gl-owner-anchor-focus s:= sn-focus-player-number)',
            f'(set-strategic-number sn-focus-player-number {p})',
            '(up-full-reset-search)', '(up-set-target-point gl-home-anchor-x)',
            '(up-filter-status c: status-ready c: list-active)',
            '(up-filter-distance c: -1 c: 24)',
            *[f'(up-find-remote c: {kind} c: 40)' for kind in LAND],
            f'(up-remove-objects search-remote object-data-player != {p})',
            '(up-remove-objects search-remote object-data-map-zone-id g:!= gl-home-zone)',
            '(up-get-search-state local-total)',
            '(up-modify-goal gl-owner-severe-count g:= remote-total)',
            '(up-modify-sn sn-focus-player-number g:= gl-owner-anchor-focus)']))
        out.append(rule(facts + ['(goal gl-home-defense-state YES)',
                                 '(up-compare-goal gl-owner-severe-count c:>= 8)',
                                 '(up-set-target-object search-remote c: 0)'], [
            '(up-modify-goal gl-owner-severe-until g:= gl-game-time)',
            '(up-modify-goal gl-owner-severe-until c:+ 45)']))
        out.append(rule(facts + ['(goal gl-home-defense-state NO)',
                                 '(up-compare-goal gl-owner-severe-count c:>= 8)',
                                 '(up-set-target-object search-remote c: 0)'], [
            '(up-get-object-data object-data-id gl-owner-severe-target)',
            f'(set-goal gl-owner-severe-player {p})',
            '(up-get-point position-object gl-owner-severe-x)',
            '(set-goal gl-owner-severe-armed YES)',
            '(set-goal gl-home-defense-state YES)',
            '(set-goal gl-local-response-state LOCAL-RESPONSE-IDLE)',
            '(up-modify-goal gl-owner-severe-until g:= gl-game-time)',
            '(up-modify-goal gl-owner-severe-until c:+ 45)']))
    out.append(rule(['(goal gl-owner-severe-armed YES)',
                     '(goal gl-owner-explore-suspended NO)'], [
        '(set-strategic-number sn-number-explore-groups 0)',
        '(set-strategic-number sn-total-number-explorers 0)',
        '(set-strategic-number sn-cap-civilian-explorers 0)',
        '(set-strategic-number sn-minimum-civilian-explorers 0)',
        '(up-modify-goal gl-command-counter-23 c:+ 1)',
        '(up-reset-scouts)', '(set-goal gl-owner-explore-suspended YES)']))
    # Preempt only compatible land military at the threatened home. Civilians,
    # remote colonies, loaded hulls and unrelated expeditions stay protected.
    for group, cancel in (
        ('attack-boarding-group', [
            '(set-goal gl-transport-route-state TRANSPORT-ROUTE-RECOVERY-WAIT)',
            '(up-set-timer c: t-transport-route c: 1)']),
        ('opportunistic-raid-group', ['(set-goal gl-raid-state RAID-IDLE)']),
        ('allied-relief-group', ['(set-goal gl-owner-relief-target -1)']),
    ):
        facts = ['(goal gl-owner-severe-armed YES)', f'(up-group-size c: {group} > 0)']
        out.append(rule(facts, [
            '(up-full-reset-search)', '(up-set-target-point gl-home-anchor-x)',
            f'(up-set-group search-local c: {group})',
            '(up-remove-objects search-local object-data-player != my-player-number)',
            f'(up-remove-objects search-local object-data-group-flag != {group})',
            '(up-get-search-state local-total)',
            '(up-modify-goal gl-owner-severe-members g:= local-total)',
            '(up-remove-objects search-local object-data-map-zone-id g:!= gl-home-zone)',
            '(up-remove-objects search-local object-data-distance > 24)',
            '(up-remove-objects search-local object-data-garrisoned == 1)',
            '(up-get-search-state local-total)']))
        out.append(rule(facts + ['(up-compare-goal local-total c:> 0)',
                                '(up-compare-goal local-total g:== gl-owner-severe-members)'], [
            *cancel, *safe_release(group),
            f'(up-chat-data-to-all owner-release-message c: {group})']))
    # The new owner acquires only after the old owners have cancelled/released.
    out.append(rule(['(goal gl-owner-severe-armed YES)'], [
        '(up-full-reset-search)', '(up-set-target-point gl-home-anchor-x)',
        '(up-add-object-by-id search-remote g: gl-owner-severe-target)',
        '(up-remove-objects search-remote object-data-player g:!= gl-owner-severe-player)',
        '(up-remove-objects search-remote object-data-status != status-ready)',
        '(up-remove-objects search-remote object-data-map-zone-id g:!= gl-home-zone)',
        '(up-remove-objects search-remote object-data-distance > 24)']))
    out.append(rule(['(goal gl-owner-severe-armed YES)', '(up-set-target-object search-remote c: 0)'],
                    safe_release('home-defense-response-group')))
    out.append(rule(['(goal gl-owner-severe-armed YES)', '(up-set-target-object search-remote c: 0)'], [
        '(up-reset-search 1 1 0 0)', '(up-set-target-point gl-home-anchor-x)',
        '(up-filter-distance c: -1 c: 32)',
        *[f'(up-find-local c: {kind} c: 40)' for kind in LAND],
        '(up-remove-objects search-local object-data-player != my-player-number)',
        '(up-remove-objects search-local object-data-group-flag >= 0)',
        '(up-remove-objects search-local object-data-map-zone-id g:!= gl-home-zone)',
        '(up-remove-objects search-local object-data-garrisoned == 1)',
        '(up-clean-search search-local object-data-distance search-order-asc)',
        '(up-remove-objects search-local object-data-index >= 16)',
        '(up-create-group 0 0 c: home-defense-response-group)',
        '(up-modify-group-flag 1 c: home-defense-response-group)',
        '(up-remove-objects search-local object-data-group-flag != home-defense-response-group)',
        '(up-target-objects 1 action-default -1 stance-aggressive)',
        '(up-chat-data-to-all owner-severe-message g: gl-owner-severe-target)']))
    out.append(rule(['(goal gl-home-defense-state YES)',
                     '(up-compare-goal gl-game-time g:>= gl-owner-severe-until)'], [
        '(set-goal gl-home-defense-state NO)']))
    return '\n\n'.join(out) + '\n'


def native_attack():
    out = [';Generated native attack admission. Called after DUC owners and before attack-now.',
           ';DE excludes a TYPE, not an object: FREE same-type units wait too.',
           ';Each loop removes a type from a finite (at most 40-member) owner list.',
           ';No movement, STOP, or reset of the already working native attack manager.']
    out.append(rule(['(true)'], ['(up-modify-goal gl-command-counter-90 c:+ 1)',
                               '(fe-reset-attack-group-exclusion-list)']))
    for group in ('siege-objective-group', 'juggernaut-bombardment-group',
                  'attack-transport-group', 'attack-boarding-group', 'home-naval-response-group',
                  'home-defense-response-group', 'opportunistic-raid-group',
                  'transport-screen-group', 'transport-escort-group',
                  'migration-transport-group', 'migration-boarding-group',
                  'recovery-transport-group', 'recovery-boarding-group',
                  'relic-ferry-transport-group', 'relic-ferry-passenger-group',
                  'naval-scout-group', 'allied-relief-group',
                  'assault-mission-1-group', 'assault-mission-2-group', 'assault-mission-3-group'):
        out.append(rule(['(true)'], [
            f'(up-set-group search-local c: {group})',
            '(up-remove-objects search-local object-data-player != my-player-number)',
            f'(up-remove-objects search-local object-data-group-flag != {group})']))
        out.append(rule(['(up-set-target-object search-local c: 0)'], [
            '(up-get-object-data object-data-type gl-owner-native-type)',
            '(up-modify-goal gl-command-counter-91 c:+ 1)',
            '(fe-exclude-from-attack-group g: gl-owner-native-type)',
            '(up-remove-objects search-local object-data-type g:== gl-owner-native-type)']))
        # RuleDelta is relative to NEXT rule: -1 repeats the jump itself.
        out.append(rule(['(up-set-target-object search-local c: 0)'], ['(up-jump-rule -2)']))
    return '\n\n'.join(out) + '\n'


def releases():
    out = [';Generated terminal releases; never issue a movement/STOP here.',
           ';Clear only living self-owned members still carrying this owner flag.']
    # The API explicitly warns that converted objects remain in cached groups.
    # Remove stale references BEFORE any controller can mutate a group flag.
    # No flag is changed while rebuilding: valid members retain the same flag;
    # other-owner/converted members retain theirs and cease to be our references.
    for group in range(20):
        out.append(rule([f'(up-group-size c: {group} > 0)'], [
            f'(up-set-group search-local c: {group})',
            '(up-remove-objects search-local object-data-player != my-player-number)',
            f'(up-remove-objects search-local object-data-group-flag != {group})',
            f'(up-create-group 0 0 c: {group})']))
    for state, idle, groups in (
        ('gl-island-migration-state', 'MIGRATION-IDLE', ('migration-boarding-group', 'migration-transport-group')),
        ('gl-transport-route-state', 'TRANSPORT-ROUTE-IDLE', ('attack-boarding-group', 'attack-transport-group')),
        ('gl-transport-recovery-state', 'TRANSPORT-RECOVERY-IDLE', ('recovery-boarding-group', 'recovery-transport-group')),
        ('gl-relic-ferry-state', 'RELIC-FERRY-IDLE', ('relic-ferry-passenger-group', 'relic-ferry-transport-group')),
    ):
        for group in groups:
            out.append(rule([f'(goal {state} {idle})', f'(up-group-size c: {group} > 0)'], safe_release(group)))
    out.append(rule(['(up-group-size c: allied-relief-group > 0)',
                     '(up-compare-goal gl-game-time g:>= gl-owner-relief-until)'],
                    safe_release('allied-relief-group')))
    # Completion/loss of the verified target releases relief before the timeout.
    out.append(rule(['(up-group-size c: allied-relief-group > 0)'], [
        '(up-full-reset-search)', '(up-add-object-by-id search-remote g: gl-owner-relief-target)',
        '(up-remove-objects search-remote object-data-player g:!= gl-owner-relief-player)',
        '(up-remove-objects search-remote object-data-status != status-ready)']))
    out.append(rule(['(up-group-size c: allied-relief-group > 0)',
                     '(not (up-set-target-object search-remote c: 0))'], safe_release('allied-relief-group')))
    return '\n\n'.join(out) + '\n'


if __name__ == '__main__':
    print('*** Begin Patch')
    emit('rawai-home-anchors.per', anchors())
    emit('rawai-severe-defense.per', severe())
    emit('rawai-owner-release.per', releases())
    emit('rawai-native-attack-ownership.per', native_attack())
    print('*** End Patch')
