"""Bounded coastal construction, using real mobile objects for path queries.

Geometry reuses the shoreline resolver's finite candidates / exact-water
validation concept. No terrain IDs, building path queries or global retasking.
AIRef cache 2026-08-30: up-path-distance option 1 requires an open exact tile;
option 0 allows vicinity. up-build-line is an issuance, NOT foundation proof.
"""
from pathlib import Path
import argparse
from generate_assault_missions import rule

ROOT = Path(__file__).resolve().parents[1]
FIELDS = ('clock', 'next', 'deficit-since', 'minimum', 'sustained',
          'sustained-since', 'admission-tier', 'reason', 'reported',
          'diag-next', 'anchor', 'sector', 'direction', 'stage', 'count', 'ship',
          'water-zone', 'zone', 'worker', 'until', 'foundation', 'memory-index',
          'anchor-x', 'anchor-y', 'w1-x', 'w1-y', 'w2-x', 'w2-y', 'w3-x', 'w3-y',
          'w4-x', 'w4-y', 'w5-x', 'w5-y', 'w6-x', 'w6-y',
          'bounded-x', 'bounded-y', 'sample', 'focus', 'attempt',
          # T51 diagnostic-only lifecycle storage.  This is a finite match-wide
          # budget; candidate retries never replenish it.
          'life-left', 'life-next', 'life-age', 'life-actual', 'life-total',
          'life-pending', 'life-ports', 'life-afford', 'life-can-build',
          'life-sustained', 'life-phase')
CANDIDATE_RADIUS = 14
MAX_CANDIDATE_ATTEMPTS = 8
SUSTAINED_SHIPYARD_CAPACITY = 4
SUSTAINED_WOOD_RESERVE = 600
DIRECTIONS = ((1,0), (0,1), (-1,0), (0,-1))
# Four independently rotated coastline sectors, each with eight dense sites.
# The sector cursor survives a completed/failed placement; a later yard starts
# on another side of its selected Port/Shipyard anchor rather than repeatedly
# filling one inlet.  All points remain inside T36's runtime-proven +/-14
# near-anchor domain and still pass the exact build/water/clearance gates below.
CANDIDATE_SECTORS = (
    ((12, 0), (10, 4), (10, -4), (14, 4), (14, -4), (8, 7), (8, -7), (14, 0)),
    ((0, 12), (4, 10), (-4, 10), (4, 14), (-4, 14), (7, 8), (-7, 8), (0, 14)),
    ((-12, 0), (-10, 4), (-10, -4), (-14, 4), (-14, -4), (-8, 7), (-8, -7), (-14, 0)),
    ((0, -12), (4, -10), (-4, -10), (4, -14), (-4, -14), (7, -8), (-7, -8), (0, -14)),
)
CANDIDATE_SPAN = len(CANDIDATE_SECTORS)


def definitions():
    names = list(FIELDS) + [f'memory{i}-{f}' for i in range(4) for f in ('x','y','until')]
    return ';Generated coastal construction storage, no timer/group allocation.\n' + '\n'.join(
        f'(defconst gl-sy-{name} {15600+i})' for i, name in enumerate(names)) + '\n'


def generate():
    out = [';Generated by tools/generate_shipyard_placement.py. Reasons: 0 satisfied,',
           ';1 unaffordable/unavailable, 2 pending, 3 missing/lost foundation,',
           ';4 worker hold/unreachable, 5 tech saving, 7 constructing,',
           ';8 no mobile water reference after minimum operational capacity,',
           ';61 no anchor, 62 candidate outside map, 63 recent-site memory,',
           ';64 candidate not buildable, 65 own-building clearance,',
           ';66 allied-building clearance, 67 water-exit validation.',
           ';Native builder assignment remains authoritative; reaching a point is not completion.']
    def add(f, a): out.append(rule(f, a))
    def stage(n): return [f'(goal gl-sy-stage {n})']
    def reset(reason): return [f'(set-goal gl-sy-reason {reason})', '(set-goal gl-sy-stage 90)']
    def retry(reason): return [f'(set-goal gl-sy-reason {reason})', '(set-goal gl-sy-stage 89)']
    def deadline(seconds): return ['(up-modify-goal gl-sy-until g:= gl-sy-clock)', f'(up-modify-goal gl-sy-until c:+ {seconds})']
    def diag(code, value, constant=False):
        scope='c:' if constant else 'g:'
        return [f'(up-chat-data-to-all str-t12-diag-id c: {code})',
                f'(up-chat-data-to-all str-t12-diag-value {scope} {value})']
    def point(name, dx, dy):
        a = [f'(up-copy-point gl-sy-{name}-x gl-shipyard-x)']
        for axis, v in (('x',dx), ('y',dy)):
            if v: a.append(f'(up-modify-goal gl-sy-{name}-{axis} c:{"+" if v>0 else "-"} {abs(v)})')
        return a
    water = '(or (goal map-type LAKE) (or (goal map-type RIVERS) (or (goal map-type ISLANDS) (goal map-type TEAM-ISLANDS))))'
    add(['(true)'], ['(set-goal gl-sy-stage 0)', '(set-goal gl-sy-next 0)',
        '(set-goal gl-sy-anchor -1)', '(set-goal gl-sy-sector 0)',
        '(set-goal gl-sy-deficit-since 0)', '(set-goal gl-sy-sustained-since 0)',
        '(set-goal gl-sy-ship -1)',
        '(set-goal gl-sy-memory-index 0)', '(set-goal gl-sy-diag-next 0)',
        '(set-goal gl-sy-reported -1)', '(set-goal gl-sy-life-left 24)',
        '(set-goal gl-sy-life-next 0)', '(set-goal gl-sy-life-phase 0)',
        *[f'(set-goal gl-sy-memory{i}-until 0)' for i in range(4)], '(disable-self)'])
    add(['(true)'], ['(up-get-fact game-time 0 gl-sy-clock)',
        '(up-modify-goal gl-sy-minimum g:= desired-number-shipyards)', '(up-modify-goal gl-sy-minimum c:min 2)',
        '(up-modify-goal gl-sy-minimum c:max 1)',
        '(up-modify-goal gl-sy-sustained g:= desired-number-shipyards)',
        f'(up-modify-goal gl-sy-sustained c:min {SUSTAINED_SHIPYARD_CAPACITY})',
        '(up-modify-goal gl-sy-sustained g:max gl-sy-minimum)',
        '(set-goal gl-sy-sample 0)'])
    for m, cap in (('LAKE',4), ('RIVERS',6)):
        add([f'(goal map-type {m})', f'(up-compare-goal desired-number-shipyards c:> {cap})'],
            [f'(up-modify-goal desired-number-shipyards c:= {cap})'])
    add(['(building-type-count shipyard g:>= gl-sy-minimum)'], ['(set-goal gl-sy-deficit-since 0)'])
    add(['(building-type-count shipyard g:>= gl-sy-sustained)'],
        ['(set-goal gl-sy-sustained-since 0)'])
    add([water, '(current-age >= early-antiquity-age)', '(building-type-count port > 0)',
         '(building-type-count shipyard g:< gl-sy-minimum)', '(goal gl-sy-deficit-since 0)'],
        ['(up-modify-goal gl-sy-deficit-since g:= gl-sy-clock)', '(up-modify-goal gl-sy-deficit-since c:+ 90)'])
    add([water, '(current-age >= middle-antiquity-age)', '(building-type-count port > 0)',
         '(building-type-count shipyard g:>= gl-sy-minimum)',
         '(building-type-count shipyard g:< gl-sy-sustained)',
         '(goal gl-sy-sustained-since 0)'],
        ['(up-modify-goal gl-sy-sustained-since g:= gl-sy-clock)',
         '(up-modify-goal gl-sy-sustained-since c:+ 180)'])
    add([*stage(0), '(up-compare-goal gl-sy-clock g:>= gl-sy-next)'],
        ['(set-goal gl-sy-sample 1)', '(set-goal gl-sy-reason 0)',
         '(set-goal gl-sy-admission-tier 0)',
         '(up-modify-goal gl-sy-next g:= gl-sy-clock)', '(up-modify-goal gl-sy-next c:+ 2)'])
    # A sixty-second, match-capped admission snapshot distinguishes absent
    # demand from resource, tech, pending and availability holds.  Searches are
    # reconstructed here and no placement/worker state is mutated.
    life=[*stage(0), '(goal gl-sy-sample 1)', '(up-compare-goal gl-sy-life-left c:> 0)',
          '(up-compare-goal gl-sy-clock g:>= gl-sy-life-next)',
          '(goal gl-sy-life-phase 0)']
    add(life,['(set-goal gl-sy-life-age 0)', '(set-goal gl-sy-life-afford 0)',
        '(set-goal gl-sy-life-can-build 0)',
        '(up-modify-goal gl-sy-life-sustained g:= gl-sy-sustained)'])
    for age, name in enumerate(('iron-age','early-antiquity-age','middle-antiquity-age','imperial-age')):
        add([*life,f'(current-age == {name})'],[f'(set-goal gl-sy-life-age {age})'])
    add([*life,'(can-afford-building shipyard)'],['(set-goal gl-sy-life-afford 1)'])
    add([*life,'(can-build shipyard)'],['(set-goal gl-sy-life-can-build 1)'])
    add(life,['(up-get-fact unit-type-count shipyard gl-sy-life-actual)',
        '(up-get-fact unit-type-count-total shipyard gl-sy-life-total)',
        '(up-get-fact unit-type-count port gl-sy-life-ports)',
        '(up-full-reset-search)', '(up-filter-status c: status-pending c: list-active)',
        '(up-find-status-local c: shipyard c: 40)', '(up-get-search-state local-total)',
        '(up-modify-goal gl-sy-life-pending g:= local-total)',
        '(set-goal gl-sy-life-phase 1)'])
    add([*stage(0), '(goal gl-sy-life-phase 1)'], [
        *diag(524,'gl-sy-life-age'), *diag(525,'desired-number-shipyards'),
        *diag(526,'gl-sy-minimum'), *diag(527,'gl-sy-life-actual'),
        *diag(528,'gl-sy-life-total'), *diag(529,'gl-sy-life-pending'),
        *diag(543,'gl-sy-life-sustained'),
        '(set-goal gl-sy-life-phase 2)'])
    add([*stage(0), '(goal gl-sy-life-phase 2)'], [
        *diag(530,'gl-sy-life-ports'), *diag(531,'wait-techup-requirements'),
        *diag(532,'gl-owner-worker-hold'), *diag(533,'gl-sy-life-afford'),
        *diag(534,'gl-sy-life-can-build'), *diag(535,'gl-sy-reason'),
        *diag(544,'gl-sy-sustained-since'),
        '(up-modify-goal gl-sy-life-next g:= gl-sy-clock)',
        '(up-modify-goal gl-sy-life-next c:+ 60)',
        '(up-modify-goal gl-sy-life-left c:- 1)',
        '(set-goal gl-sy-life-phase 0)'])
    common = [*stage(0), '(goal gl-sy-sample 1)', water, '(current-age >= early-antiquity-age)',
              '(building-type-count port > 0)', '(goal shipyard-placement-state SHIPYARD-IDLE)']
    # Preserve the high-priority first-yard opening, including its wood reserve.
    add([*common, '(building-type-count-total shipyard == 0)', '(wood-amount > 250)',
         '(up-pending-objects c: shipyard <= 0)', '(not (up-pending-placement c: shipyard))',
         '(can-build shipyard)'], ['(set-goal gl-sy-admission-tier 1)',
                                  '(set-goal shipyard-placement-state SHIPYARD-ANCHOR)'])
    add([*common, '(goal wait-techup-requirements NO)', '(can-afford-building shipyard)',
         '(building-type-count-total shipyard g:< desired-number-shipyards)',
         '(up-pending-objects c: shipyard <= 0)', '(not (up-pending-placement c: shipyard))',
         '(can-build shipyard)'], ['(set-goal gl-sy-admission-tier 4)',
                                  '(set-goal shipyard-placement-state SHIPYARD-ANCHOR)'])
    # Only a persistent deficit BELOW min(desired,2) bypasses the policy hold.
    # No escrow release: available resources must still pay the actual cost.
    add([*common, '(goal wait-techup-requirements YES)', '(building-type-count-total shipyard >= 1)',
         '(building-type-count-total shipyard g:< gl-sy-minimum)', '(goal gl-owner-worker-hold NO)',
         '(up-compare-goal gl-sy-deficit-since c:> 0)', '(up-compare-goal gl-sy-clock g:>= gl-sy-deficit-since)',
         '(can-afford-building shipyard)', '(can-build shipyard)',
         '(up-pending-objects c: shipyard <= 0)', '(not (up-pending-placement c: shipyard))'],
        ['(set-goal gl-sy-admission-tier 2)',
         '(set-goal shipyard-placement-state SHIPYARD-ANCHOR)'])
    # The source-visible post-minimum gate previously left every yard above two
    # behind an indefinitely renewable tech-up hold.  Protect a bounded
    # sustained-war tier (at most four) only after a longer deficit and while
    # retaining a substantial wood reserve; full desired expansion remains on
    # ordinary policy.  This neither releases escrow nor disables tech saving.
    add([*common, '(goal wait-techup-requirements YES)',
         '(building-type-count-total shipyard g:>= gl-sy-minimum)',
         '(building-type-count-total shipyard g:< gl-sy-sustained)',
         '(goal gl-owner-worker-hold NO)',
         '(up-compare-goal gl-sy-sustained-since c:> 0)',
         '(up-compare-goal gl-sy-clock g:>= gl-sy-sustained-since)',
         f'(wood-amount > {SUSTAINED_WOOD_RESERVE})',
         '(can-afford-building shipyard)', '(can-build shipyard)',
         '(up-pending-objects c: shipyard <= 0)',
         '(not (up-pending-placement c: shipyard))'],
        ['(set-goal gl-sy-admission-tier 3)',
         '(set-goal shipyard-placement-state SHIPYARD-ANCHOR)'])
    for facts, reason in ((['(goal wait-techup-requirements YES)'],5),
            (['(not (can-build shipyard))'],1), (['(goal gl-owner-worker-hold YES)'],4),
            (['(or (up-pending-objects c: shipyard >= 1) (up-pending-placement c: shipyard))'],2)):
        add([*common, '(building-type-count shipyard g:< gl-sy-minimum)', *facts], [f'(set-goal gl-sy-reason {reason})'])
    add([*stage(0), '(goal shipyard-placement-state SHIPYARD-ANCHOR)'], [
        '(set-goal gl-sy-attempt 0)',
        '(up-full-reset-search)', '(up-filter-status c: status-ready c: list-active)',
        '(up-find-local c: port c: 40)', '(up-find-local c: shipyard c: 40)',
        '(up-remove-objects search-local object-data-id g:<= gl-sy-anchor)',
        '(up-clean-search search-local object-data-id search-order-asc)', '(set-goal gl-sy-stage 1)'])
    add([*stage(1), '(up-set-target-object search-local c: 0)'], [
        '(up-get-object-data object-data-id gl-sy-anchor)', '(up-get-point position-object gl-sy-anchor-x)',
        '(set-goal gl-sy-stage 2)'])
    # Cursor exhaustion is not absence. Rebuild once without the cursor and
    # wrap to the first ready anchor without consuming a candidate or failed
    # site-memory entry. Only an empty rebuilt list is a real reason 61.
    add(stage(1), ['(up-full-reset-search)', '(up-filter-status c: status-ready c: list-active)',
        '(up-find-local c: port c: 40)', '(up-find-local c: shipyard c: 40)',
        '(up-clean-search search-local object-data-id search-order-asc)', '(set-goal gl-sy-stage 11)'])
    add([*stage(11), '(up-set-target-object search-local c: 0)'], [
        '(up-get-object-data object-data-id gl-sy-anchor)', '(up-get-point position-object gl-sy-anchor-x)',
        '(set-goal gl-sy-stage 2)'])
    add(stage(11), ['(set-goal gl-sy-anchor -1)', *reset(61)])
    # T50 showed that random +/-14 sampling makes valid coast discovery slow
    # and can repeatedly rediscover a narrow local inlet.  Enumerate a finite
    # dense sector instead.  The eight-attempt lane remains the hard bound;
    # success or exhaustion rotates the next admission to another sector.
    for sector, offsets in enumerate(CANDIDATE_SECTORS):
        for attempt, (dx, dy) in enumerate(offsets):
            actions = ['(up-copy-point gl-shipyard-x gl-sy-anchor-x)']
            if dx:
                actions.append(f'(up-modify-goal gl-shipyard-x c:{"+" if dx > 0 else "-"} {abs(dx)})')
            if dy:
                actions.append(f'(up-modify-goal gl-shipyard-y c:{"+" if dy > 0 else "-"} {abs(dy)})')
            actions += ['(up-bound-point gl-sy-bounded-x gl-shipyard-x)',
                        '(set-goal gl-sy-direction 0)', '(set-goal gl-sy-stage 3)']
            add([*stage(2), f'(goal gl-sy-sector {sector})',
                 f'(goal gl-sy-attempt {attempt})'], actions)
    add([*stage(3), '(or (up-compare-goal gl-shipyard-x g:!= gl-sy-bounded-x) (up-compare-goal gl-shipyard-y g:!= gl-sy-bounded-y))'], retry(62))
    for i in range(4):
        add([*stage(3), f'(up-compare-goal gl-sy-clock g:< gl-sy-memory{i}-until)'], [
            '(up-set-target-point gl-shipyard-x)', f'(up-get-point-distance gl-sy-memory{i}-x 0 gl-sy-count)'])
        add([*stage(3), f'(up-compare-goal gl-sy-clock g:< gl-sy-memory{i}-until)', '(up-compare-goal gl-sy-count c:< 10)'], retry(63))
    add([*stage(3), '(not (up-can-build-line 0 gl-shipyard-x c: shipyard))'], retry(64))
    add(stage(3), ['(up-full-reset-search)', '(up-set-target-point gl-shipyard-x)',
        '(up-filter-distance c: -1 c: 10)', '(up-find-local c: port c: 40)', '(up-find-local c: shipyard c: 40)',
        '(up-reset-search 1 0 0 0)',
        '(up-filter-status c: status-pending c: list-active)', '(up-find-status-local c: shipyard c: 40)',
        '(up-get-search-state local-total)', '(set-goal gl-sy-stage 4)'])
    add([*stage(4), '(up-compare-goal local-total c:> 0)'], retry(65))
    add(stage(4), ['(up-modify-goal gl-sy-focus s:= sn-focus-player-number)', '(set-goal gl-sy-zone 0)'])
    for p in range(1,9):
        allied=[*stage(4),'(goal gl-sy-zone 0)',f'(stance-toward {p} ally)']
        add(allied,[f'(set-strategic-number sn-focus-player-number {p})', '(up-full-reset-search)',
            '(up-set-target-point gl-shipyard-x)', '(up-filter-distance c: -1 c: 10)',
            '(up-find-remote c: port c: 40)', '(up-find-remote c: shipyard c: 40)',
            '(up-get-search-state local-total)'])
        add([*allied,'(up-compare-goal remote-total c:> 0)'],['(set-goal gl-sy-zone 1)'])
    add(stage(4), ['(up-modify-sn sn-focus-player-number g:= gl-sy-focus)'])
    add([*stage(4),'(goal gl-sy-zone 1)'],retry(66))
    # A fleet that has sailed more than 64 tiles from home remains a valid
    # reachability probe, as does a mobile Trade Cog produced by the Port. The
    # exact path checks below still require the chosen hull to reach every
    # sampled water tile, so widening discovery does not waive coast quality.
    add(stage(4), ['(up-full-reset-search)', '(up-set-target-point gl-shipyard-x)',
        '(up-filter-distance c: -1 c: 255)', '(up-find-local c: warship-class c: 40)',
        '(up-find-local c: transport-ship c: 40)', '(up-find-local c: fishing-ship-class c: 40)',
        '(up-find-local c: trade-cog-class c: 40)',
        '(up-clean-search search-local object-data-distance search-order-asc)', '(set-goal gl-sy-stage 5)'])
    add([*stage(5), '(up-set-target-object search-local c: 0)'], [
        '(up-get-object-data object-data-id gl-sy-ship)',
        '(up-get-object-data object-data-map-zone-id gl-sy-water-zone)', '(set-goal gl-sy-stage 6)'])
    # The first/second Shipyard must not be circularly dependent on already
    # owning a nearby ship. Admission has already enforced the high-priority
    # first-yard or persistent minimum-deficit policy. In the exceptional
    # no-probe case, retain build-line, separation and worker-path validation;
    # only the mobile four-point water proof is unavailable. Later expansion
    # beyond the minimum remains blocked until a real mobile probe exists.
    add([*stage(5), '(not (up-set-target-object search-local c: 0))',
         '(building-type-count-total shipyard g:< gl-sy-minimum)'], [
        '(set-goal gl-sy-ship -1)', '(set-goal gl-sy-direction 0)',
        '(set-goal gl-sy-stage 6)'])
    add(stage(5), reset(8))
    # Test four orientations, never manufacture water by clipping a land tile.
    for i,(dx,dy) in enumerate(DIRECTIONS):
        add([*stage(6), f'(goal gl-sy-direction {i})'], [
            *point('w1',dx*6,dy*6), *point('w2',dx*12,dy*12),
            *point('w3',dx*12-dy*4,dy*12+dx*4), *point('w4',dx*12+dy*4,dy*12-dx*4),
            *point('w5',dx*6-dy*6,dy*6+dx*6), *point('w6',dx*6+dy*6,dy*6-dx*6),
            '(set-goal gl-sy-stage 7)'])
    # Far-end reachability alone can route around a local throat. The two W1
    # lateral probes require a twelve-tile aperture immediately in front of the
    # foundation before that orientation can qualify as open water.
    for point_name in ('w1','w2','w3','w4','w5','w6'):
        x=f'gl-sy-{point_name}-x'
        add([*stage(7), '(up-compare-goal gl-sy-ship c:>= 0)'],
            [f'(up-bound-point gl-sy-bounded-x {x})', f'(up-get-point-zone {x} gl-sy-zone)',
            '(up-full-reset-search)', '(up-add-object-by-id search-local g: gl-sy-ship)'])
        add([*stage(7), '(up-compare-goal gl-sy-ship c:< 0)'],
            [f'(up-bound-point gl-sy-bounded-x {x})'])
        add([*stage(7), f'(or (up-compare-goal {x} g:!= gl-sy-bounded-x) (up-compare-goal {x[:-1]}y g:!= gl-sy-bounded-y))'], ['(set-goal gl-sy-stage 8)'])
        add([*stage(7), '(up-compare-goal gl-sy-ship c:>= 0)', '(up-compare-goal gl-sy-zone g:!= gl-sy-water-zone)'], ['(set-goal gl-sy-stage 8)'])
        add([*stage(7), '(up-compare-goal gl-sy-ship c:>= 0)', '(not (up-set-target-object search-local c: 0))'], ['(set-goal gl-sy-stage 8)'])
        add([*stage(7), '(up-compare-goal gl-sy-ship c:>= 0)', '(up-set-target-object search-local c: 0)', '(up-object-data object-data-player != my-player-number)'], ['(set-goal gl-sy-stage 8)'])
        add([*stage(7), '(up-compare-goal gl-sy-ship c:>= 0)', '(up-set-target-object search-local c: 0)', f'(up-path-distance {x} 1 == 65535)'], ['(set-goal gl-sy-stage 8)'])
    add(stage(8), ['(up-modify-goal gl-sy-direction c:+ 1)', '(set-goal gl-sy-stage 6)'])
    add([*stage(6), '(up-compare-goal gl-sy-direction c:>= 4)'], retry(67))
    # A geometric miss is not an admission failure. Keep the already-admitted
    # placement lane and test a bounded batch around the same ready anchor.
    # Only exhaustion releases the controller and records failed-site memory.
    add([*stage(89), f'(up-compare-goal gl-sy-attempt c:< {MAX_CANDIDATE_ATTEMPTS - 1})'], [
        '(up-modify-goal gl-sy-attempt c:+ 1)', '(set-goal gl-sy-stage 2)'])
    add([*stage(89), f'(up-compare-goal gl-sy-attempt c:>= {MAX_CANDIDATE_ATTEMPTS - 1})'], [
        '(set-goal gl-sy-stage 90)'])
    add(stage(7), ['(up-full-reset-search)', '(up-set-target-point gl-shipyard-x)',
        '(up-filter-distance c: -1 c: 40)', '(up-find-local c: villager-class c: 40)',
        '(up-remove-objects search-local object-data-player != my-player-number)',
        '(up-remove-objects search-local object-data-group-flag >= 0)',
        '(up-remove-objects search-local object-data-garrisoned == 1)',
        '(up-remove-objects search-local object-data-under-attack > 0)',
        '(up-remove-objects search-local object-data-action == actionid-build)',
        '(up-remove-objects search-local object-data-action == actionid-repair)',
        '(up-remove-objects search-local object-data-id g:== gl-boar-lurer-id)',
        '(up-clean-search search-local object-data-distance search-order-asc)', '(set-goal gl-sy-stage 9)'])
    add([*stage(9), '(up-set-target-object search-local c: 0)', '(up-path-distance gl-shipyard-x 0 < 64)'], [
        '(up-get-object-data object-data-id gl-sy-worker)', '(set-goal gl-sy-stage 10)'])
    add(stage(9), reset(4))
    add([*stage(10), '(goal gl-owner-worker-hold NO)', '(can-build shipyard)', '(can-afford-building shipyard)',
         '(up-compare-goal gl-sy-admission-tier c:> 0)',
         '(or (building-type-count-total shipyard == 0) (building-type-count-total shipyard g:< desired-number-shipyards))',
         '(up-pending-objects c: shipyard <= 0)', '(not (up-pending-placement c: shipyard))',
         '(up-can-build-line 0 gl-shipyard-x c: shipyard)',
         '(up-compare-goal gl-sy-life-left c:> 0)'], [
        # Writer fingerprint at the exact build-line issuance boundary.
        *diag(536,'gl-shipyard-x'), *diag(537,'gl-shipyard-y'),
        *diag(538,'gl-sy-anchor'), *diag(539,'gl-sy-worker'),
        *diag(540,'gl-sy-attempt'), '(up-modify-goal gl-sy-life-left c:- 1)'])
    add([*stage(10), '(goal gl-owner-worker-hold NO)', '(can-build shipyard)', '(can-afford-building shipyard)',
         '(up-compare-goal gl-sy-admission-tier c:> 0)',
         '(or (building-type-count-total shipyard == 0) (building-type-count-total shipyard g:< desired-number-shipyards))',
         '(up-pending-objects c: shipyard <= 0)', '(not (up-pending-placement c: shipyard))',
         '(up-can-build-line 0 gl-shipyard-x c: shipyard)'], [
        '(up-build-line gl-shipyard-x gl-shipyard-x c: shipyard)', *deadline(24),
        '(set-goal gl-sy-foundation -1)', '(set-goal gl-sy-stage 20)'])
    add(stage(10), reset(4))
    # Pending count anywhere is not proof: verify the actual own object at issue.
    add(stage(20), ['(up-full-reset-search)', '(up-set-target-point gl-shipyard-x)',
        '(up-filter-distance c: -1 c: 2)', '(up-filter-status c: status-pending c: list-active)',
        '(up-find-status-local c: shipyard c: 40)', '(up-reset-search 1 0 0 0)',
        '(up-filter-status c: status-ready c: list-active)',
        '(up-find-status-local c: shipyard c: 40)', '(set-goal gl-sy-stage 21)'])
    add([*stage(21), '(up-set-target-object search-local c: 0)',
         '(up-object-data object-data-player == my-player-number)',
         '(up-compare-goal gl-sy-life-left c:> 0)'], [
        '(up-get-object-data object-data-id gl-sy-foundation)',
        *diag(541,'gl-sy-foundation'), *diag(542,1,True),
        '(up-modify-goal gl-sy-life-left c:- 1)'])
    add([*stage(21), '(up-set-target-object search-local c: 0)', '(up-object-data object-data-player == my-player-number)'], [
        '(up-get-object-data object-data-id gl-sy-foundation)', '(set-goal gl-sy-reason 7)', *deadline(180), '(set-goal gl-sy-stage 22)'])
    add([*stage(21), '(up-compare-goal gl-sy-clock g:>= gl-sy-until)'], reset(3))
    add(stage(21), ['(set-goal gl-sy-stage 20)'])
    add(stage(22), ['(up-full-reset-search)', '(up-add-object-by-id search-local g: gl-sy-foundation)'])
    add([*stage(22), '(up-set-target-object search-local c: 0)',
         '(up-object-data object-data-player == my-player-number)',
         '(up-object-data object-data-status == status-ready)',
         '(up-compare-goal gl-sy-life-left c:> 0)'], [
        *diag(541,'gl-sy-foundation'), *diag(542,2,True),
        '(up-modify-goal gl-sy-life-left c:- 1)'])
    add([*stage(22), '(up-set-target-object search-local c: 0)', '(up-object-data object-data-player == my-player-number)',
         '(up-object-data object-data-status == status-ready)'], ['(set-goal gl-sy-reason 0)', '(set-goal gl-sy-stage 91)'])
    add([*stage(22), '(not (up-set-target-object search-local c: 0))'], reset(3))
    add([*stage(22), '(up-compare-goal gl-sy-clock g:>= gl-sy-until)'], reset(4))
    for i in range(4):
        add([*stage(90), f'(goal gl-sy-memory-index {i})'], [
            f'(up-copy-point gl-sy-memory{i}-x gl-shipyard-x)', f'(up-modify-goal gl-sy-memory{i}-until g:= gl-sy-clock)',
            f'(up-modify-goal gl-sy-memory{i}-until c:+ 180)', '(set-goal gl-sy-stage 91)'])
    add(stage(91), ['(up-modify-goal gl-sy-memory-index c:+ 1)', '(up-modify-goal gl-sy-memory-index c:mod 4)',
        '(up-modify-goal gl-sy-sector c:+ 1)', f'(up-modify-goal gl-sy-sector c:mod {CANDIDATE_SPAN})',
        '(set-goal gl-sy-admission-tier 0)',
        '(set-goal shipyard-placement-state SHIPYARD-IDLE)', '(set-goal gl-sy-stage 0)'])
    add(['(up-compare-goal gl-sy-clock g:>= gl-sy-diag-next)', '(up-compare-goal gl-sy-reason g:!= gl-sy-reported)',
         '(up-compare-goal gl-sy-life-left c:> 0)'], [
        '(up-chat-data-to-all str-t12-diag-id c: 410)', '(up-chat-data-to-all str-t12-diag-value g: gl-sy-reason)',
        '(up-modify-goal gl-sy-reported g:= gl-sy-reason)', '(up-modify-goal gl-sy-diag-next g:= gl-sy-clock)',
        '(up-modify-goal gl-sy-diag-next c:+ 60)', '(up-modify-goal gl-sy-life-left c:- 1)'])
    return '\n\n'.join(out)+'\n'


def outputs():
    return {'rawai-shipyard-defs.per': definitions(), 'rawai-specialplacement.per': generate()}


if __name__ == '__main__':
    parser=argparse.ArgumentParser(); parser.add_argument('--write',action='store_true'); args=parser.parse_args()
    for name, text in outputs().items():
        path=ROOT/name
        if args.write: path.write_text(text, encoding='utf-8')
        elif not path.exists() or path.read_text(encoding='utf-8-sig') != text: raise SystemExit(f'stale: {name}')
