"""Narrow safe-island exception to the aggregate land-superiority admission gate.

The existing three-slot loader, cadence, enemy selection, screening, landing and
voyage controllers are unchanged. A read-only safety census supplies a short
lease; each actual manifest re-counts eligible home troops and keeps a reserve.
"""
from pathlib import Path
import argparse
from generate_assault_missions import rule

ROOT=Path(__file__).resolve().parents[1]
FIELDS=('clock','next','until','safe-after','allowed','stage','worker','blocked','focus',
        'target-x','target-y','free','reserve','manifest-limit','siege-keep','reported','diag-next','naval-pressure',
        # T51 diagnostic-only, finite match-wide lifecycle samples.
        'life-left','life-next','life-total','life-blocker','life-budget-reported')
CLASSES=('scout-cavalry-class','cavalry-archer-class','cavalry-class','infantry-class','archery-class','siege-weapon-class')


def definitions():
    return ';Generated expedition admission goals; existing 3 mission records unchanged.\n'+'\n'.join(
        f'(defconst gl-exp-{key} {15900+i})' for i,key in enumerate(FIELDS))+'\n'


def generate():
    out=[';Generated by tools/generate_expedition_admission.py.',
         ';No objective/mission/order mutations. Safety lease expires after 35s;',
         ';home/near-coast threats impose a fresh 180s quiet period.']
    def add(f,a):out.append(rule(f,a))
    def diag(code,value,constant=False):
        scope='c:' if constant else 'g:'
        return [f'(up-chat-data-to-all str-t12-diag-id c: {code})',
                f'(up-chat-data-to-all str-t12-diag-value {scope} {value})']
    add(['(true)'],['(up-get-fact game-time 0 gl-exp-clock)', '(set-goal gl-exp-next 0)',
        '(set-goal gl-exp-until 0)', '(set-goal gl-exp-allowed NO)', '(set-goal gl-exp-stage 0)',
        '(up-modify-goal gl-exp-safe-after g:= gl-exp-clock)', '(up-modify-goal gl-exp-safe-after c:+ 180)',
        '(set-goal gl-exp-reported -1)', '(set-goal gl-exp-diag-next 0)',
        '(set-goal gl-exp-life-left 24)', '(set-goal gl-exp-life-next 0)',
        '(set-goal gl-exp-life-budget-reported 0)', '(disable-self)'])
    add(['(true)'],['(up-get-fact game-time 0 gl-exp-clock)', '(set-goal gl-exp-allowed NO)'])
    for f in ('(goal gl-home-defense-state YES)','(goal gl-self-attack-verified YES)'):
        add([f],['(up-modify-goal gl-exp-safe-after g:= gl-exp-clock)', '(up-modify-goal gl-exp-safe-after c:+ 180)'])
    add(['(up-compare-goal gl-exp-clock g:>= gl-exp-next)', '(current-age >= middle-antiquity-age)',
         '(up-compare-goal gl-home-zone c:>= 0)'],['(up-modify-goal gl-exp-next g:= gl-exp-clock)',
        '(up-modify-goal gl-exp-next c:+ 30)', '(set-goal gl-exp-blocked YES)', '(set-goal gl-exp-naval-pressure NO)',
        '(set-goal gl-exp-worker -1)',
        '(up-modify-goal gl-exp-focus s:= sn-focus-player-number)', '(up-full-reset-search)',
        '(up-set-target-point gl-home-anchor-x)', '(up-find-local c: villager-class c: 40)',
        '(up-remove-objects search-local object-data-map-zone-id g:!= gl-home-zone)',
        '(up-remove-objects search-local object-data-garrisoned == 1)',
        '(up-clean-search search-local object-data-distance search-order-asc)', '(set-goal gl-exp-stage 1)'])
    add(['(goal gl-exp-stage 1)', '(up-set-target-object search-local c: 0)'],[
        '(up-get-object-data object-data-id gl-exp-worker)', '(set-goal gl-exp-blocked NO)', '(set-goal gl-exp-stage 2)'])
    # A same-zone enemy is a conservative veto. Cross-zone roads are additionally
    # checked with a real local worker, never a Market or an assumed zone equivalence.
    for p in range(1,9):
        scan=['(goal gl-exp-stage 2)',f'(player-in-game {p})',f'(stance-toward {p} enemy)']
        add(scan,[f'(set-strategic-number sn-focus-player-number {p})', '(up-full-reset-search)',
            '(up-set-target-point gl-home-anchor-x)', '(up-filter-distance c: -1 c: 40)',
            '(up-find-remote c: warship-class c: 40)', '(up-find-remote c: transport-ship c: 40)',
            '(up-get-search-state local-total)'])
        add([*scan,'(up-compare-goal remote-total c:> 0)'],['(set-goal gl-exp-naval-pressure YES)'])
        candidates=['(up-full-reset-search)', '(up-set-target-point gl-home-anchor-x)',
            '(up-find-remote c: town-center c: 20)', '(up-find-remote c: castle c: 20)',
            '(up-find-remote c: villager-class c: 40)', '(up-find-remote c: infantry-class c: 40)',
            '(up-find-remote c: cavalry-class c: 40)', '(up-find-remote c: archery-class c: 40)',
            '(up-clean-search search-remote object-data-distance search-order-asc)']
        # A fifth known home-zone candidate must not disappear merely because
        # the expensive cross-zone mobile path checks are capped at four.
        add(scan,[*candidates, '(up-remove-objects search-remote object-data-map-zone-id g:!= gl-home-zone)',
            '(up-get-search-state local-total)'])
        add([*scan,'(up-compare-goal remote-total c:> 0)'],['(set-goal gl-exp-blocked YES)'])
        add([*scan,'(goal gl-exp-blocked NO)'],candidates)
        for index in range(4):
            check=[*scan,'(goal gl-exp-blocked NO)', f'(up-set-target-object search-remote c: {index})']
            add([*check,'(up-object-data object-data-map-zone-id g:== gl-home-zone)'],['(set-goal gl-exp-blocked YES)'])
            add(check,['(up-get-point position-object gl-exp-target-x)', '(up-reset-search 1 1 0 0)',
                '(up-add-object-by-id search-local g: gl-exp-worker)'])
            add([*check,'(up-set-target-object search-local c: 0)', '(up-object-data object-data-player == my-player-number)',
                 '(up-path-distance gl-exp-target-x 0 != 65535)'],['(set-goal gl-exp-blocked YES)'])
    add(['(goal gl-exp-stage 2)','(goal gl-exp-naval-pressure YES)'],[
        '(up-modify-goal gl-exp-safe-after g:= gl-exp-clock)', '(up-modify-goal gl-exp-safe-after c:+ 180)'])
    life=['(up-compare-goal gl-exp-stage c:> 0)', '(up-compare-goal gl-exp-life-left c:> 0)',
          '(up-compare-goal gl-exp-clock g:>= gl-exp-life-next)']
    add(life,['(set-goal gl-exp-life-blocker 0)', '(up-get-fact soldier-count 0 gl-exp-life-total)'])
    add([*life,'(goal gl-exp-worker -1)'],['(set-goal gl-exp-life-blocker 1)'])
    add([*life,'(goal gl-exp-blocked YES)'],['(set-goal gl-exp-life-blocker 2)'])
    add([*life,'(goal gl-exp-naval-pressure YES)'],['(set-goal gl-exp-life-blocker 3)'])
    add([*life,'(up-compare-goal gl-exp-clock g:< gl-exp-safe-after)'],['(set-goal gl-exp-life-blocker 4)'])
    add([*life,'(up-compare-goal gl-ap-seed-enemy c:< 1)'],['(set-goal gl-exp-life-blocker 5)'])
    add([*life,'(up-compare-goal naval-superiority c:< TOLERABLE)'],['(set-goal gl-exp-life-blocker 6)'])
    add([*life,'(unit-type-count warship-class < 2)'],['(set-goal gl-exp-life-blocker 7)'])
    add([*life,'(unit-type-count transport-ship < 1)'],['(set-goal gl-exp-life-blocker 8)'])
    add(life,[*diag(600,'gl-exp-stage'), *diag(601,'gl-exp-life-blocker'),
        *diag(602,'gl-exp-life-total'), *diag(603,'gl-exp-worker'),
        *diag(604,'gl-exp-blocked'), *diag(605,'gl-exp-naval-pressure'),
        *diag(606,'gl-exp-safe-after'), *diag(607,'gl-ap-seed-enemy'),
        *diag(608,'naval-superiority'), *diag(609,'gl-am1-state'),
        *diag(610,'gl-am2-state'), *diag(611,'gl-am3-state'),
        *diag(612,'gl-transport-route-state'),
        '(up-modify-goal gl-exp-life-next g:= gl-exp-clock)',
        '(up-modify-goal gl-exp-life-next c:+ 60)',
        '(up-modify-goal gl-exp-life-left c:- 1)'])
    add(['(up-compare-goal gl-exp-stage c:> 0)'],['(up-modify-sn sn-focus-player-number g:= gl-exp-focus)',
        '(up-modify-goal gl-exp-until g:= gl-exp-clock)', '(up-modify-goal gl-exp-until c:+ 35)', '(set-goal gl-exp-stage 0)'])
    add(['(up-compare-goal gl-exp-clock g:< gl-exp-until)', '(up-compare-goal gl-exp-clock g:>= gl-exp-safe-after)',
         '(goal gl-exp-blocked NO)', '(goal gl-exp-naval-pressure NO)', '(goal gl-home-defense-state NO)',
         '(goal gl-self-attack-verified NO)', '(up-compare-goal gl-ap-seed-enemy c:>= 1)',
         '(up-compare-goal naval-superiority c:>= TOLERABLE)', '(unit-type-count warship-class >= 2)',
         '(unit-type-count transport-ship >= 1)'],['(set-goal gl-exp-allowed YES)'])
    add(['(up-compare-goal gl-exp-clock g:>= gl-exp-diag-next)', '(up-compare-goal gl-exp-allowed g:!= gl-exp-reported)'],[
        '(up-chat-data-to-all str-t12-diag-id c: 430)', '(up-chat-data-to-all str-t12-diag-value g: gl-exp-allowed)',
        '(up-modify-goal gl-exp-reported g:= gl-exp-allowed)', '(up-modify-goal gl-exp-diag-next g:= gl-exp-clock)',
        '(up-modify-goal gl-exp-diag-next c:+ 60)'])
    return '\n\n'.join(out)+'\n'


def budget():
    f=['(goal gl-transport-route-state TRANSPORT-ROUTE-MANIFEST-FIND)', '(goal gl-exp-allowed YES)']
    out=[';Generated same-pass census: all counts are FREE eligible idle HOME troops,',
         ';not global military, not garrisoned passengers, not already-owned soldiers.']
    def add(f,a):out.append(rule(f,a))
    def diag(code,value):return [f'(up-chat-data-to-all str-t12-diag-id c: {code})',
                                 f'(up-chat-data-to-all str-t12-diag-value g: {value})']
    add(['(not (goal gl-transport-route-state TRANSPORT-ROUTE-MANIFEST-FIND))'],[
        '(set-goal gl-exp-life-budget-reported 0)'])
    add(f,['(set-goal gl-exp-free 0)'])
    for kind in CLASSES:
        # Census each class separately: a 40-result manifest search is not an
        # army count. Respect the documented 240-object local search capacity.
        add(f,['(up-full-reset-search)','(up-set-target-point gl-home-anchor-x)',
        f'(up-find-local c: {kind} c: 240)',
        '(up-remove-objects search-local object-data-type == palintonon)',
        '(up-remove-objects search-local object-data-type == palintonon-packed)',
        '(up-remove-objects search-local object-data-player != my-player-number)',
        '(up-remove-objects search-local object-data-group-flag >= 0)',
        '(up-remove-objects search-local object-data-garrisoned == 1)',
        '(up-remove-objects search-local object-data-idling != 1)',
        '(up-remove-objects search-local object-data-under-attack > 0)',
        '(up-remove-objects search-local object-data-order == orderid-enter)',
        '(up-remove-objects search-local object-data-map-zone-id g:!= gl-home-zone)',
        '(up-get-search-state local-total)', '(up-modify-goal gl-exp-free g:+ local-total)'])
    # The final census is the siege class, so keep one eligible specialist.
    add([*f,'(up-set-target-object search-local c: 0)'],['(up-get-object-data object-data-id gl-exp-siege-keep)'])
    add(f,['(up-modify-goal gl-exp-reserve g:= gl-exp-free)', '(up-modify-goal gl-exp-reserve c:/ 4)',
        '(up-modify-goal gl-exp-reserve c:max 12)'])
    add([*f,'(up-compare-goal naval-superiority c:< EQUAL)'],[
        '(up-modify-goal gl-exp-reserve g:= gl-exp-free)', '(up-modify-goal gl-exp-reserve c:/ 2)',
        '(up-modify-goal gl-exp-reserve c:max 20)', '(set-goal gl-exp-manifest-limit 5)'])
    add(f,['(up-modify-goal gl-exp-free g:- gl-exp-reserve)', '(up-modify-goal gl-exp-free c:max 0)',
        '(up-modify-goal gl-exp-manifest-limit g:min gl-exp-free)'])
    add([*f,'(goal gl-exp-life-budget-reported 0)', '(up-compare-goal gl-exp-life-left c:> 0)'],[
        *diag(613,'gl-exp-life-total'), *diag(614,'gl-exp-free'),
        *diag(615,'gl-exp-reserve'), *diag(616,'gl-exp-manifest-limit'),
        '(set-goal gl-exp-life-budget-reported 1)', '(up-modify-goal gl-exp-life-left c:- 1)'])
    return '\n\n'.join(out)+'\n'


def outputs(): return {'rawai-expedition-defs.per':definitions(), 'rawai-expedition-admission.per':generate(), 'rawai-expedition-budget.per':budget()}


if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--write',action='store_true');args=parser.parse_args()
    for name,text in outputs().items():
        path=ROOT/name
        if args.write:path.write_text(text,encoding='utf-8')
        elif not path.exists() or path.read_text(encoding='utf-8-sig')!=text:raise SystemExit(f'stale: {name}')
