"""Generate bounded, observation-only boarding telemetry; no gameplay orders."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
NAMES = ['local','local-last','remote','remote-last','issued-actor','issued',
         'next','left','state','actor','hull','writer','due','action','target',
         'order','garrisoned','carry','group','observed','expires']
LABELS = ['writer','modifier','hull','local-count','actor-candidate','time',
          'post-actor','post-hull','post-writer','post-modifier','post-observed',
          'post-time','post-mission-state','post-action','post-target','post-order',
          'post-garrisoned','post-carry','post-group','remote-count']

def rule(facts, actions):
    return '(defrule\n\t' + '\n\t'.join(facts) + '\n=>\n\t' + '\n\t'.join(actions) + '\n)\n'

def chat(label, value):
    code = 700 + LABELS.index(label)
    return (f'(up-chat-data-to-all str-t12-diag-id c: {code}) ; boarding {label}\n\t'
            f'(up-chat-data-to-all str-t12-diag-value {value})')

def render():
    defs = ';Generated by tools/generate_boarding_ctrl_diag.py.\n'
    defs += '\n'.join(f'(defconst gl-board-diag-{n} {15838+i})' for i,n in enumerate(NAMES)) + '\n'
    init = rule(['(true)'],[f'(set-goal gl-board-diag-{n} 0)' for n in NAMES]+['(disable-self)'])
    capture = ';Generated. Runs AFTER issuance; never changes search lists or gameplay goals.\n'
    capture += rule(['(goal gl-board-diag-issued 20)'], [
        '(up-chat-data-to-all "RAW44C migration terminal phase: %d" c: 3)'])
    capture += rule(['(up-compare-goal gl-board-diag-issued c:> 0)',
        '(up-compare-goal gl-game-time g:>= gl-board-diag-next)'],[
        '(set-goal gl-board-diag-left 8)',
        '(up-modify-goal gl-board-diag-next g:= gl-game-time)',
        '(up-modify-goal gl-board-diag-next c:+ 300)'])
    capture += rule(['(up-compare-goal gl-board-diag-issued c:> 0)',
        '(up-compare-goal gl-board-diag-left c:> 0)'],[
        chat('writer','g: gl-board-diag-issued'), chat('modifier','c: 2'),
        chat('hull','g: gl-island-migration-transport-id'),
        chat('local-count','g: gl-board-diag-local'),
        chat('remote-count','g: gl-board-diag-remote'),
        chat('actor-candidate','g: gl-board-diag-issued-actor'),
        chat('time','g: gl-game-time'),
        '(up-modify-goal gl-board-diag-left c:- 1)'])
    # The search-count validity guard prevents stale target pointers after an
    # empty selection from being presented as a commanded actor.
    capture += rule(['(up-compare-goal gl-board-diag-issued c:> 0)',
        '(up-compare-goal gl-board-diag-local c:> 0)',
        '(up-compare-goal gl-board-diag-remote c:> 0)',
        '(up-compare-goal gl-board-diag-left c:> 0)',
        '(goal gl-board-diag-state 0)'],[
        '(up-modify-goal gl-board-diag-actor g:= gl-board-diag-issued-actor)',
        '(up-modify-goal gl-board-diag-hull g:= gl-island-migration-transport-id)',
        '(up-modify-goal gl-board-diag-writer g:= gl-board-diag-issued)',
        '(up-modify-goal gl-board-diag-due g:= gl-game-time)',
        '(up-modify-goal gl-board-diag-due c:+ 2)',
        '(up-modify-goal gl-board-diag-expires g:= gl-game-time)',
        '(up-modify-goal gl-board-diag-expires c:+ 60)',
        '(set-goal gl-board-diag-state 1)'])
    capture += rule(['(up-compare-goal gl-board-diag-issued c:> 0)'],[
        '(set-goal gl-board-diag-issued 0)'])

    post = ';Generated. Farm IDLE timer boundary, before its existing reset/search.\n'
    post += rule(['(goal gl-board-diag-state 2)',
        '(up-compare-goal gl-game-time g:>= gl-board-diag-next)'],[
        '(set-goal gl-board-diag-state 0)'])
    post += rule(['(goal gl-board-diag-state 1)',
        '(up-compare-goal gl-game-time g:>= gl-board-diag-due)',
        '(up-timer-status t-farm-staffing == timer-triggered)',
        '(goal gl-farm-staffing-state FARM-STAFFING-IDLE)'],[
        '(up-full-reset-search)', '(fe-filter-garrisoned c: 1)',
        '(up-add-object-by-id search-local g: gl-board-diag-actor)',
        '(up-remove-objects search-local object-data-player != my-player-number)',
        '(set-goal gl-board-diag-observed 0)',
        '(set-goal gl-board-diag-state 3)'])
    post += rule(['(goal gl-board-diag-state 3)',
        '(up-set-target-object search-local c: 0)'],[
        f'(up-get-object-data object-data-{field} gl-board-diag-{goal})'
        for field,goal in [('action','action'),('target-id','target'),('order','order'),
                           ('garrisoned','garrisoned'),('carry','carry'),('group-flag','group')]
        ]+['(set-goal gl-board-diag-observed 1)'])
    post += rule(['(goal gl-board-diag-state 3)'],[
        chat('post-actor','g: gl-board-diag-actor'),chat('post-hull','g: gl-board-diag-hull'),
        chat('post-writer','g: gl-board-diag-writer'),chat('post-modifier','c: 2'),
        chat('post-observed','g: gl-board-diag-observed'),chat('post-time','g: gl-game-time'),
        chat('post-mission-state','g: gl-island-migration-state'),
        '(set-goal gl-board-diag-state 4)'])
    post += rule(['(goal gl-board-diag-state 4)','(goal gl-board-diag-observed 1)'],[
        chat('post-'+n,'g: gl-board-diag-'+n)
        for n in ['action','target','order','garrisoned','carry','group']])
    post += rule(['(goal gl-board-diag-state 4)'],[
        '(up-full-reset-search)', '(set-goal gl-board-diag-state 2)'])
    post += rule(['(goal gl-board-diag-state 1)',
        '(up-compare-goal gl-game-time g:>= gl-board-diag-expires)'],[
        chat('post-actor','g: gl-board-diag-actor'),chat('post-hull','g: gl-board-diag-hull'),
        chat('post-writer','g: gl-board-diag-writer'),chat('post-modifier','c: 2'),
        chat('post-observed','c: -1'),chat('post-time','g: gl-game-time'),
        '(set-goal gl-board-diag-state 2)'])
    return {'rawai-boarding-ctrl-defs.per':defs,'rawai-boarding-ctrl-init.per':init,
            'rawai-boarding-ctrl-capture.per':capture,'rawai-boarding-ctrl-post.per':post}

if __name__ == '__main__':
    for name,text in render().items():
        path=ROOT/name
        if '--write' in sys.argv:
            path.write_bytes(text.replace('\n','\r\n').encode())
        elif not path.exists() or path.read_text(encoding='utf-8-sig') != text:
            raise SystemExit(f'out of sync: {name}')
    print('boarding diagnostic generation: PASS')
