"""Emit apply_patch input for bounded STOP/native-writer counters.

Counters record source invocations, including empty selections. Zero invocations
can rule a writer out; a positive count alone cannot attribute a native packet.
No duplicated predicates, rule insertion in writers, or relative-jump changes.
"""
from pathlib import Path
import difflib
import re
from validate_naval_doctrine import rule_blocks

ROOT = Path(__file__).resolve().parents[1]
STRIP = re.compile(r'\t; RAW12 counter \d+\n\t\(up-modify-goal gl-command-counter-\d+ c:\+ 1\)\n')


def render():
    result, sites = {}, []
    # Keep existing writer IDs stable across an inserted controller. T14 packet
    # comparisons depend on these IDs; only newly added sites get new numbers.
    existing = {}
    for path in sorted(ROOT.glob('*.per')):
        for _, _, body, _, actions in rule_blocks(path.read_text(encoding='utf-8-sig')):
            if 'action-stop' not in actions and '(up-reset-scouts)' not in actions:
                continue
            found = re.findall(r'up-modify-goal gl-command-counter-(\d+) c:\+ 1', actions)
            if found:
                existing[path.name, STRIP.sub('', body)] = int(found[0])
    next_code = max(existing.values(), default=0) + 1
    for path in sorted(ROOT.glob('*.per')):
        if path.name.startswith('rawai-command-counter'):
            continue
        old = path.read_text(encoding='utf-8-sig')
        base = STRIP.sub('', old)
        edits = []
        for a, b, body, facts, actions in rule_blocks(base):
            if 'action-stop' not in actions and '(up-reset-scouts)' not in actions:
                continue
            code = existing.get((path.name, body))
            if code is None:
                code, next_code = next_code, next_code + 1
            kind = 'reset-scouts' if '(up-reset-scouts)' in actions else 'STOP'
            sites.append((code, path.name, kind, ' '.join(facts.split())[:170]))
            command = re.search(r'\((?:up-target-(?:point|objects)[^\n]*action-stop[^\n]*|up-reset-scouts)\)', body)
            assert command, (path, kind)
            at = base.rfind('\n', 0, a + command.start()) + 1
            if path.name != 'rawai-severe-defense.per':
                edits.append((at, f'\t; RAW12 counter {code}\n\t(up-modify-goal gl-command-counter-{code} c:+ 1)\n'))
        for where, extra in reversed(edits):
            base = base[:where] + extra + base[where:]
        # Native aggregate counters are generated by the ownership generator.
        if path.name != 'rawai-native-attack-ownership.per' and base != old:
            result[path.name] = base
    sites.sort(key=lambda site: site[0])
    sites += [(90, 'rawai-native-attack-ownership.per', 'reset attack exclusions', 'aggregate'),
              (91, 'rawai-native-attack-ownership.per', 'exclude attack type', 'aggregate')]
    defs = [';Generated by tools/instrument_command_counters.py; see source map below.',
            '(defconst gl-command-counter-clock 14000)',
            '(defconst gl-command-counter-next 14001)',
            '(defconst str-command-counter-id "RAW12 writer id: %d")',
            '(defconst str-command-counter-count "RAW12 writer count: %d")']
    for code, file, kind, facts in sites:
        defs += [f'; {code}: {file}, {kind}: {facts}',
                 f'(defconst gl-command-counter-{code} {14100+code})']
    for start in range(0, len(sites), 20):
        defs += ['(defrule\n\t(true)\n=>',
                 *[f'\t(set-goal gl-command-counter-{code} 0)' for code, *_ in sites[start:start+20]],
                 '\t(disable-self)\n)']
    defs += ['(defrule\n\t(true)\n=>\n\t(set-goal gl-command-counter-next 60)\n\t(disable-self)\n)']
    result['rawai-command-counter-defs.per'] = '\n'.join(defs) + '\n'
    report = [';Generated once-per-minute nonzero source invocation counters.',
              ';No lifetime quota; never changes targets, searches, groups, or orders.',
              '(defrule\n\t(true)\n=>\n\t(up-get-fact game-time 0 gl-command-counter-clock)\n)']
    for code, *_ in sites:
        report += [f'''(defrule
\t(up-compare-goal gl-command-counter-clock g:>= gl-command-counter-next)
\t(up-compare-goal gl-command-counter-{code} c:> 0)
=>
\t(up-chat-data-to-all str-command-counter-id c: {code})
\t(up-chat-data-to-all str-command-counter-count g: gl-command-counter-{code})
\t(set-goal gl-command-counter-{code} 0)
)''']
    report += ['''(defrule
\t(up-compare-goal gl-command-counter-clock g:>= gl-command-counter-next)
=>
\t(up-modify-goal gl-command-counter-next g:= gl-command-counter-clock)
\t(up-modify-goal gl-command-counter-next c:+ 60)
)''']
    result['rawai-command-counters.per'] = '\n\n'.join(report) + '\n'
    return result


if __name__ == '__main__':
    print('*** Begin Patch')
    for name, value in render().items():
        p = ROOT / name
        if not p.exists():
            print('*** Add File: ' + p.as_posix())
            print('\n'.join('+' + s for s in value.splitlines()))
        elif p.read_text(encoding='utf-8-sig') != value:
            old = p.read_text(encoding='utf-8-sig').splitlines()
            print('*** Update File: ' + p.as_posix())
            # Repeated states need full context, not ambiguous tiny hunks.
            print('\n'.join('@@' if s.startswith('@@') else s for s in
                  list(difflib.unified_diff(old, value.splitlines(), n=16))[2:]))
    print('*** End Patch')
